{{- if .Values.v8kopi.enabled }}
---
# ServiceAccount for V8-Kopi
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "jamaibase.fullname" $ }}-{{ .Values.v8kopi.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.v8kopi.name }}
    {{- include "jamaibase.labels" . | nindent 4 }}
---
# Role for V8-Kopi to manage pods
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "jamaibase.fullname" $ }}-{{ .Values.v8kopi.rbac.roleName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.v8kopi.name }}
    {{- include "jamaibase.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "patch", "delete"]
---
# RoleBinding for V8-Kopi ServiceAccount
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "jamaibase.fullname" $ }}-{{ .Values.v8kopi.rbac.roleName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.v8kopi.name }}
    {{- include "jamaibase.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "jamaibase.fullname" $ }}-{{ .Values.v8kopi.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "jamaibase.fullname" $ }}-{{ .Values.v8kopi.rbac.roleName }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
