{{- if empty .Values.core.databaseSecretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: cryostat-jmx-credentials-db
type: Opaque
data:
  CRYOSTAT_JMX_CREDENTIALS_DB_PASSWORD: {{ include "cryostat.databasePassword" . }}
{{- end -}}
