latestversion: '10.0'
releases:
  '10.0':
    platform: 'UBI 9'
    sdkdoc: 'https://github.com/redhat-developer/s2i-dotnetcore/tree/main/10.0/build/README.md'
    sdkrepository: 'registry.access.redhat.com/ubi9/dotnet-100'
    runtimedoc: 'https://github.com/redhat-developer/s2i-dotnetcore/tree/main/10.0/runtime/README.md'
    runtimerepository: 'registry.access.redhat.com/ubi9/dotnet-100-runtime'
    aspnetdoc: 'https://github.com/redhat-developer/s2i-dotnetcore/tree/main/10.0/aspnet/README.md'
    aspnetrepository: 'registry.access.redhat.com/ubi9/dotnet-100-aspnet'
  '9.0':
    platform: 'UBI 8'
    sdkdoc: 'https://github.com/redhat-developer/s2i-dotnetcore/tree/main/9.0/build/README.md'
    sdkrepository: 'registry.access.redhat.com/ubi8/dotnet-90'
    runtimedoc: 'https://github.com/redhat-developer/s2i-dotnetcore/tree/main/9.0/runtime/README.md'
    runtimerepository: 'registry.access.redhat.com/ubi8/dotnet-90-runtime'
    aspnetdoc: 'https://github.com/redhat-developer/s2i-dotnetcore/tree/main/9.0/runtime/README.md'
    aspnetrepository: 'registry.access.redhat.com/ubi8/dotnet-90-runtime'
  '8.0':
    platform: 'UBI 8'
    sdkdoc: 'https://github.com/redhat-developer/s2i-dotnetcore/tree/main/8.0/build/README.md'
    sdkrepository: 'registry.access.redhat.com/ubi8/dotnet-80'
    runtimedoc: 'https://github.com/redhat-developer/s2i-dotnetcore/tree/main/8.0/runtime/README.md'
    runtimerepository: 'registry.access.redhat.com/ubi8/dotnet-80-runtime'
    aspnetdoc: 'https://github.com/redhat-developer/s2i-dotnetcore/tree/main/8.0/runtime/README.md'
    aspnetrepository: 'registry.access.redhat.com/ubi8/dotnet-80-runtime'