apiversion: v1
kind: verify-report
metadata:
    tool:
        verifier-version: 1.13.13
        profile:
            VendorType: partner
            version: v1.3
        reportDigest: uint64:2383097837922272243
        chart-uri: N/A
        digests:
            chart: sha256:e50e1fb27a3c35c13a260e6d74987b2c58b661f31f25ac134fbb435c4850d922
            package: 0dc4f5899003ce77b19ed2ae4bb98b317671900e5f9499e6bd1df33577f9e758
        lastCertifiedTimestamp: "2025-09-16T06:18:26.594634+00:00"
        testedOpenShiftVersion: "4.18"
        supportedOpenShiftVersions: '>=4.7'
        webCatalogOnly: true
    chart:
        name: cmm-operator-k8s
        home: ""
        sources: []
        version: 25.7.0-p1
        description: A Helm chart for CMM in Kubernetes using operators
        keywords: []
        maintainers: []
        icon: https://www.nokia.com/chart-icon.png
        apiversion: v2
        condition: ""
        tags: ""
        appversion: ""
        deprecated: false
        annotations:
            charts.openshift.io/archs: x86_64
            charts.openshift.io/name: Nokia CMM
            charts.openshift.io/provider: Nokia
            charts.openshift.io/supportURL: https://github.com/nokiacmm/helm-chart
        kubeversion: '>= 1.20.0-0'
        dependencies: []
        type: application
    chart-overrides: ""
results:
    - check: v1.0/contains-values
      type: Mandatory
      outcome: PASS
      reason: Values file exist
    - check: v1.1/images-are-certified
      type: Mandatory
      outcome: PASS
      reason: 'Image is Red Hat certified : quay.io/nepravee/cmm-operator:CMM25.7.0.0'
    - check: v1.0/required-annotations-present
      type: Mandatory
      outcome: PASS
      reason: All required annotations present
    - check: v1.0/signature-is-valid
      type: Mandatory
      outcome: SKIPPED
      reason: 'Chart is not signed : Signature verification not required'
    - check: v1.0/contains-values-schema
      type: Mandatory
      outcome: PASS
      reason: Values schema file exist
    - check: v1.0/has-readme
      type: Mandatory
      outcome: PASS
      reason: Chart has a README
    - check: v1.0/helm-lint
      type: Mandatory
      outcome: PASS
      reason: Helm lint successful
    - check: v1.0/is-helm-v3
      type: Mandatory
      outcome: PASS
      reason: API version is V2, used in Helm 3
    - check: v1.0/not-contain-csi-objects
      type: Mandatory
      outcome: PASS
      reason: CSI objects do not exist
    - check: v1.0/has-notes
      type: Optional
      outcome: PASS
      reason: Chart does contain NOTES.txt
    - check: v1.0/not-contains-crds
      type: Mandatory
      outcome: PASS
      reason: Chart does not contain CRDs
    - check: v1.0/chart-testing
      type: Mandatory
      outcome: PASS
      reason: Chart tests have passed
    - check: v1.0/contains-test
      type: Mandatory
      outcome: PASS
      reason: Chart test files exist
    - check: v1.1/has-kubeversion
      type: Mandatory
      outcome: PASS
      reason: Kubernetes version specified

