### CMF application, by default assumes that the service account has cluster wide access.
{{- if .Values.rbac }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    {{- include "cmf.labels" . | nindent 4 }}
  name: {{ include "cmf.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "cmf.name" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "cmf.name" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}