apiversion: v1
kind: verify-report
metadata:
  tool:
    verifier-version: 1.2.3
    profile:
      VendorType: partner
      version: v1.0
    chart-uri: /charts/stable/ibm-oms-pro-case-bundle/charts/ibm-oms-pro-prod
    digest: sha256:5ef57b10f8b72f04f1a38b7e07c657687342f50db75ef812d720986bc14c9b97
    digests:
      chart: sha256:5ef57b10f8b72f04f1a38b7e07c657687342f50db75ef812d720986bc14c9b97
    lastCertifiedTimestamp: '2021-09-30T00:20:11.381803+00:00'
    certifiedOpenShiftVersions: 4.8.0
  chart:
    name: ibm-oms-pro-prod
    home: http://ibm.biz/oms-home
    sources: []
    version: 6.0.2
    description: IBM Order management Software Professional Edition v10 provides
      cross-channel order orchestration capabilities to enable intelligent brokering
      of orders across many disparate systems. It also provides a global view
      of inventory across the supply chain and enables business users to make
      changes to order process. Documentation For additional details regarding
      install parameters check http://ibm.biz/oms-helm-readme. License By installing
      this product you accept the license terms http://ibm.biz/oms-license and
      http://ibm.biz/oms-apps-license.
    keywords:
      - oms
      - sterling
      - yantra
      - order
      - fulfillment
      - om
      - amd64
      - ppc64le
      - framework
      - Commercial
      - RHOCP
      - IKS
      - Other
    maintainers:
      - name: IBM
        email: ''
        url: ''
    icon: https://raw.githubusercontent.com/IBM/charts/master/logo/ibm-oms-logo.png
    apiversion: v2
    condition: ''
    tags: ''
    appversion: 10.0.0
    deprecated: false
    annotations: {}
    kubeversion: '>=1.16.0-0'
    dependencies:
      - name: ibm-sch
        version: 1.2.15
        repository: '@sch'
        condition: ''
        tags: []
        enabled: false
        importvalues: []
        alias: sch
    type: application
  chart-overrides: ''
results:
  - check: v1.0/has-readme
    type: Mandatory
    outcome: PASS
    reason: Chart has a README
  - check: v1.0/contains-test
    type: Mandatory
    outcome: PASS
    reason: Chart test files exist
  - check: v1.0/contains-values-schema
    type: Mandatory
    outcome: PASS
    reason: Values schema file exist
  - check: v1.0/helm-lint
    type: Mandatory
    outcome: PASS
    reason: Helm lint successful
  - check: v1.0/images-are-certified
    type: Mandatory
    outcome: PASS
    reason: |-
      Image is Red Hat certified : cp.icr.io/cp/ibm-oms-professional/om-app:10.0.0.23-amd64
      Image is Red Hat certified : cp.icr.io/cp/ibm-oms-professional/om-agent:10.0.0.23-amd64
  - check: v1.0/is-helm-v3
    type: Mandatory
    outcome: PASS
    reason: API version is V2, used in Helm 3
  - check: v1.0/contains-values
    type: Mandatory
    outcome: PASS
    reason: Values file exist
  - check: v1.0/has-kubeversion
    type: Mandatory
    outcome: PASS
    reason: Kubernetes version specified
  - check: v1.0/not-contains-crds
    type: Mandatory
    outcome: PASS
    reason: Chart does not contain CRDs
  - check: v1.0/not-contain-csi-objects
    type: Mandatory
    outcome: PASS
    reason: CSI objects do not exist
  - check: v1.0/chart-testing
    type: Mandatory
    outcome: PASS
    reason: Chart tests have passed
