apiversion: v1
kind: verify-report
metadata:
    tool:
        verifier-version: 1.13.12
        profile:
            VendorType: partner
            version: v1.3
        reportDigest: uint64:18222340911716800294
        chart-uri: i2i-5gcore-1.0.9.tgz
        digests:
            chart: sha256:a3fcebd7e3c46940507479bd57bc7c5be106cf23b592842fd1ffe471808ab7d4
            package: 027e9e2d3901eb134bcccb9a461a80b3a67de9003201f8c79b7b6ca9a9e24d1f
            publicKey: aa99eb4a941b04a955aefb682f5180899ab2feaf9a72ddc6a02f2dc118f36889
        lastCertifiedTimestamp: "2025-07-02T16:34:24.023995+03:00"
        testedOpenShiftVersion: "4.18"
        supportedOpenShiftVersions: '>=4.6'
        webCatalogOnly: false
    chart:
        name: i2i-5gcore
        home: ""
        sources: []
        version: 1.0.9
        description: A Helm chart for Kubernetes
        keywords: []
        maintainers: []
        icon: https://i2i-systems.com/wp-content/uploads/2020/02/i2i_logo.png
        apiversion: v2
        condition: ""
        tags: ""
        appversion: 1.12.0
        deprecated: false
        annotations:
            charts.openshift.io/name: i2i-5G-Core
        kubeversion: '>=1.19.0-0'
        dependencies: []
        type: application
    chart-overrides: ""
results:
    - check: v1.1/images-are-certified
      type: Mandatory
      outcome: PASS
      reason: |-
        Image is Red Hat certified : quay.io/i2i/ausf-app-ubi9:latest
        Image is Red Hat certified : quay.io/i2i/nssf-app-ubi9:latest
        Image is Red Hat certified : registry.access.redhat.com/ubi8/ubi
        Image is Red Hat certified : quay.io/i2i/upf-app-ubi8:1.12.0
        Image is Red Hat certified : quay.io/i2i/amf-app-ubi9:latest
        Image is Red Hat certified : quay.io/i2i/nrf-app-ubi9:latest
        Image is Red Hat certified : quay.io/i2i/pcf-app-ubi9:latest
        Image is Red Hat certified : quay.io/i2i/smf-app-ubi9:latest
        Image is Red Hat certified : quay.io/i2i/udm-app-ubi9:latest
        Image is Red Hat certified : quay.io/i2i/udr-app-ubi9:latest
    - check: v1.0/is-helm-v3
      type: Mandatory
      outcome: PASS
      reason: API version is V2, used in Helm 3
    - check: v1.1/has-kubeversion
      type: Mandatory
      outcome: PASS
      reason: Kubernetes version specified
    - check: v1.0/helm-lint
      type: Mandatory
      outcome: PASS
      reason: Helm lint successful
    - check: v1.0/contains-values
      type: Mandatory
      outcome: PASS
      reason: Values file exist
    - check: v1.0/has-notes
      type: Optional
      outcome: PASS
      reason: Chart does contain NOTES.txt
    - check: v1.0/contains-values-schema
      type: Mandatory
      outcome: PASS
      reason: Values schema file exist
    - check: v1.0/has-readme
      type: Mandatory
      outcome: PASS
      reason: Chart has a README
    - check: v1.0/signature-is-valid
      type: Mandatory
      outcome: PASS
      reason: 'Chart is signed : Signature verification passed'
    - check: v1.0/required-annotations-present
      type: Mandatory
      outcome: PASS
      reason: All required annotations present
    - check: v1.0/not-contains-crds
      type: Mandatory
      outcome: PASS
      reason: Chart does not contain CRDs
    - check: v1.0/chart-testing
      type: Mandatory
      outcome: PASS
      reason: Chart tests have passed
    - check: v1.0/not-contain-csi-objects
      type: Mandatory
      outcome: PASS
      reason: CSI objects do not exist
    - check: v1.0/contains-test
      type: Mandatory
      outcome: PASS
      reason: Chart test files exist
