Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
apiversion: v1
kind: verify-report
metadata:
    tool:
        verifier-version: 1.0.0
        profile:
            VendorType: partner
            version: v1.1
        chart-uri: /charts/_build/wavefront-1.13.0.tgz
        digests:
            chart: sha256:7c8f5d0ea4eb7f9672c7d49d59169adb7859ea8bc8837cb5f089704a84f7984f
            package: fd3723819deaea72526da3225b8360a1acd94df1af49d450c424a01b36569fd9
        lastCertifiedTimestamp: "2022-12-21T00:08:46.958038+00:00"
        testedOpenShiftVersion: "4.9"
        supportedOpenShiftVersions: '>=4.6'
        providerControlledDelivery: false
    chart:
        name: wavefront
        home: https://www.wavefront.com
        sources:
            - https://github.com/wavefrontHQ/wavefront-collector-for-kubernetes
            - https://github.com/wavefrontHQ/wavefront-proxy
        version: 1.13.0
        description: Wavefront Collector for Kubernetes
        keywords:
            - metric
            - monitoring
            - observability
            - alerting
        maintainers:
            - name: akodali18
              email: akodali@vmware.com
              url: ""
            - name: johncornish
              email: jcornish@vmware.com
              url: ""
            - name: josephgee
              email: jgee@vmware.com
              url: ""
            - name: helen-shao
              email: shaoh@vmware.com
              url: ""
            - name: mceldeen
              email: matthewco@vmware.com
              url: ""
            - name: mmichael
              email: mamichael@vmware.com
              url: ""
            - name: priyaselvaganesan
              email: pselvaganesa@vmware.com
              url: ""
        icon: ""
        apiversion: v2
        condition: ""
        tags: ""
        appversion: 1.13.0
        deprecated: false
        annotations:
            charts.openshift.io/name: wavefront
        kubeversion: '>= 1.19'
        dependencies:
            - name: kube-state-metrics
              version: ^4.16.0
              repository: https://prometheus-community.github.io/helm-charts
              condition: kubeStateMetrics.enabled
              tags: []
              enabled: false
              importvalues: []
              alias: ""
        type: ""
    chart-overrides: ""
results:
    - check: v1.0/is-helm-v3
      type: Mandatory
      outcome: PASS
      reason: API version is V2, used in Helm 3
    - check: v1.0/contains-test
      type: Mandatory
      outcome: PASS
      reason: Chart test files exist
    - check: v1.1/has-kubeversion
      type: Mandatory
      outcome: PASS
      reason: Kubernetes version specified
    - check: v1.0/helm-lint
      type: Mandatory
      outcome: PASS
      reason: Helm lint successful
    - check: v1.0/contains-values-schema
      type: Mandatory
      outcome: PASS
      reason: Values schema file exist
    - check: v1.0/contains-values
      type: Mandatory
      outcome: PASS
      reason: Values file exist
    - check: v1.0/chart-testing
      type: Mandatory
      outcome: PASS
      reason: Chart tests have passed
    - check: v1.0/has-readme
      type: Mandatory
      outcome: PASS
      reason: Chart has a README
    - check: v1.0/not-contain-csi-objects
      type: Mandatory
      outcome: PASS
      reason: CSI objects do not exist
    - check: v1.0/images-are-certified
      type: Mandatory
      outcome: PASS
      reason: |-
        Image is Red Hat certified : registry.connect.redhat.com/wavefronthq/wavefront-kubernetes-collector:1.13.0
        Image is Red Hat certified : registry.connect.redhat.com/wavefronthq/proxy:11.3
        Image is Red Hat certified : registry.connect.redhat.com/seldonio/kubectl
    - check: v1.0/not-contains-crds
      type: Mandatory
      outcome: PASS
      reason: Chart does not contain CRDs
    - check: v1.0/required-annotations-present
      type: Mandatory
      outcome: PASS
      reason: All required annotations present
