{{- if .Values.victoriaMetrics.enabled }}
{{- if .Values.victoriaMetrics.vmauth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: vm-secret-jamaibase
    app.kubernetes.io/part-of: vm-operator
    {{- include "jamaibase.labels" . | nindent 4 }}
  name: {{ .Values.victoriaMetrics.vmuser.secretName }}
type: Opaque
data:
  password: {{ .Values.victoriaMetrics.vmuser.password | b64enc }}
{{- end }}
{{- end }}
