apiversion: v1
kind: verify-report
metadata:
    tool:
        verifier-version: 1.12.2
        profile:
            VendorType: partner
            version: v1.2
        reportDigest: uint64:11391008800145432894
        chart-uri: N/A
        digests:
            chart: sha256:cf66a5b6893c5913b389800f8a2749d01ad1034b24cb3e9e85f54a108459304e
            package: 1de931424834c6887c6b61815c229b7615a3a9194fdcf5e1730b945f3beb5f40
        lastCertifiedTimestamp: "2025-12-03T15:30:10.237458+00:00"
        testedOpenShiftVersion: 4.16.20
        supportedOpenShiftVersions: '>=4.8'
        webCatalogOnly: true
    chart:
        name: 5g-mongodb-upf-global
        home: ""
        sources: []
        version: 25.2.570-20250814.9942493
        description: A Helm chart for 5G Core MongoDB(for UPF NE)(25/08/14)
        keywords: []
        maintainers: []
        icon: ""
        apiversion: v2
        condition: ""
        tags: ""
        appversion: 25.B.0
        deprecated: false
        annotations:
            charts.openshift.io/archs: x86_64
            charts.openshift.io/name: 5g-mongodb-upf-global-25b
            charts.openshift.io/provider: Samsung Electronics
            charts.openshift.io/releaseDate: 25/08/14
            charts.openshift.io/supportURL: https://www.samsung.com/global/business/networks/contact-us/
        kubeversion: '>= 1.21.0-0'
        dependencies:
            - name: mdbm
              version: 13.2.0
              repository: ""
              condition: mdbm.enabled
              tags: []
              enabled: false
              importvalues: []
              alias: ""
        type: ""
    chart-overrides: ""
results:
    - check: v1.0/contains-values-schema
      type: Mandatory
      outcome: PASS
      reason: Values schema file exist
    - check: v1.0/contains-values
      type: Mandatory
      outcome: PASS
      reason: Values file exist
    - check: v1.1/has-kubeversion
      type: Mandatory
      outcome: PASS
      reason: Kubernetes version specified
    - check: v1.0/helm-lint
      type: Mandatory
      outcome: PASS
      reason: Helm lint successful
    - check: v1.0/is-helm-v3
      type: Mandatory
      outcome: PASS
      reason: API version is V2, used in Helm 3
    - check: v1.0/not-contain-csi-objects
      type: Mandatory
      outcome: PASS
      reason: CSI objects do not exist
    - check: v1.1/images-are-certified
      type: Mandatory
      outcome: FAIL
      reason: |-
        Image is not Red Hat certified : quay.samsung.bos2.lab/samsung_5gc/mongodb-7.0:13.2.0
        Image is not Red Hat certified : quay.samsung.bos2.lab/samsung_5gc/global-nf-ima:SVR25B_20250814_9942493
    - check: v1.0/not-contains-crds
      type: Mandatory
      outcome: PASS
      reason: Chart does not contain CRDs
    - check: v1.0/signature-is-valid
      type: Mandatory
      outcome: SKIPPED
      reason: 'Chart is not signed : Signature verification not required'
    - check: v1.0/chart-testing
      type: Mandatory
      outcome: PASS
      reason: Chart tests have passed
    - check: v1.0/contains-test
      type: Mandatory
      outcome: PASS
      reason: Chart test files exist
    - check: v1.0/required-annotations-present
      type: Mandatory
      outcome: PASS
      reason: All required annotations present
    - check: v1.0/has-readme
      type: Mandatory
      outcome: PASS
      reason: Chart has a README
