apiVersion: v1
kind: Secret
metadata:
  name: diffgram-walrus-secrets
type: Opaque
stringData:
  STRIPE_API_KEY: {{ .Values.diffgramSecrets.STRIPE_API_KEY }}
  DIFFGRAM_AWS_ACCESS_KEY_SECRET: {{ .Values.diffgramSecrets.DIFFGRAM_AWS_ACCESS_KEY_SECRET }}
  DIFFGRAM_AWS_ACCESS_KEY_ID: {{ .Values.diffgramSecrets.DIFFGRAM_AWS_ACCESS_KEY_ID }}
  _ANALYTICS_WRITE_KEY: {{ .Values.diffgramSecrets._ANALYTICS_WRITE_KEY }}
  MAILGUN_KEY: {{ .Values.diffgramSecrets.MAILGUN_KEY }}
  HUB_SPOT_KEY: {{ .Values.diffgramSecrets.HUB_SPOT_KEY }}
  FERNET_KEY: {{ .Values.diffgramSecrets.FERNET_KEY }}
  SECRET_KEY: {{ .Values.diffgramSecrets.SECRET_KEY }}
  INTER_SERVICE_SECRET: {{ .Values.diffgramSecrets.INTER_SERVICE_SECRET }}
  {{ if eq .Values.dbSettings.dbProvider "local"}}
  DATABASE_URL:  "postgresql+psycopg2://{{ .Values.dbSettings.dbUser }}:{{ .Values.dbSettings.dbPassword }}@diffgram-postgres/{{ .Values.dbSettings.dbName }}"
  {{ end }}
  {{ if eq .Values.dbSettings.dbProvider "rds"}}
  DATABASE_URL:  "postgresql+psycopg2://{{ .Values.dbSettings.dbUser }}:{{ .Values.dbSettings.dbPassword }}@postgres-rds-service/{{ .Values.dbSettings.dbName }}"
  {{ end }}
  {{ if eq .Values.dbSettings.dbProvider "azure"}}
  DATABASE_URL:  "postgresql+psycopg2://{{ .Values.dbSettings.dbUser }}:{{ .Values.dbSettings.dbPassword }}@postgres-azure-service/{{ .Values.dbSettings.dbName }}"
  {{ end }}
  USER_PASSWORDS_SECRET:  {{ .Values.diffgramSecrets.USER_PASSWORDS_SECRET }}
  DIFFGRAM_AZURE_CONNECTION_STRING:  {{ .Values.diffgramSecrets.DIFFGRAM_AZURE_CONNECTION_STRING }}