apiversion: v1
kind: verify-report
metadata:
    tool:
        verifier-version: 1.13.13
        profile:
            VendorType: partner
            version: v1.3
        reportDigest: uint64:12227100595316347943
        chart-uri: ./kubevault-certified-2026.1.8-rc.0.tgz
        digests:
            chart: sha256:91778efbb304f971a9dddfdab4d7ca18dc3dbfd11aec8a8115fe0333d874d354
            package: ceec67e00fff56ca21d17b55c608eb242142ca5faa18a19821aeaa30f8dcd82d
        lastCertifiedTimestamp: "2026-01-22T12:29:16.762341+06:00"
        testedOpenShiftVersion: "4.18"
        supportedOpenShiftVersions: '>=4.15'
        webCatalogOnly: false
    chart:
        name: kubevault-certified
        home: https://kubevault.com
        sources:
            - https://github.com/kubevault
        version: 2026.1.8-rc.0
        description: KubeVault by AppsCode - HashiCorp Vault operator for Kubernetes
        keywords: []
        maintainers:
            - name: appscode
              email: support@appscode.com
              url: ""
        icon: https://cdn.appscode.com/images/products/kubevault/kubevault-icon.png
        apiversion: v2
        condition: ""
        tags: ""
        appversion: v2026.1.8-rc.0
        deprecated: false
        annotations:
            charts.openshift.io/name: kubevault-certified
        kubeversion: '>=1.28.0'
        dependencies:
            - name: kubevault-crds
              version: v2026.1.8-rc.0
              repository: file://../kubevault-crds
              condition: kubevault-crds.enabled
            - name: kubevault-catalog
              version: v2026.1.8-rc.0
              repository: file://../kubevault-catalog
              condition: kubevault-catalog.enabled
            - name: kubevault-operator
              version: v0.24.0-rc.0
              repository: file://../kubevault-operator
              condition: kubevault-operator.enabled
            - name: kubevault-webhook-server
              version: v0.24.0-rc.0
              repository: file://../kubevault-webhook-server
              condition: kubevault-webhook-server.enabled
            - name: ace-user-roles
              version: v2025.3.14
              repository: oci://ghcr.io/appscode-charts
              condition: ace-user-roles.enabled
        type: application
    chart-overrides: ""
results:
    - check: v1.0/is-helm-v3
      type: Mandatory
      outcome: PASS
      reason: API version is V2, used in Helm 3
    - check: v1.0/not-contain-csi-objects
      type: Mandatory
      outcome: PASS
      reason: CSI objects do not exist
    - check: v1.0/required-annotations-present
      type: Mandatory
      outcome: PASS
      reason: All required annotations present
    - check: v1.0/contains-test
      type: Mandatory
      outcome: PASS
      reason: Chart test files exist
    - check: v1.1/has-kubeversion
      type: Mandatory
      outcome: PASS
      reason: Kubernetes version specified
    - check: v1.0/chart-testing
      type: Mandatory
      outcome: PASS
      reason: Chart tests have passed
    - check: v1.0/contains-values-schema
      type: Mandatory
      outcome: PASS
      reason: Values schema file exist
    - check: v1.0/has-notes
      type: Optional
      outcome: PASS
      reason: Chart does contain NOTES.txt
    - check: v1.0/not-contains-crds
      type: Mandatory
      outcome: PASS
      reason: Chart does not contain CRDs
    - check: v1.0/signature-is-valid
      type: Mandatory
      outcome: SKIPPED
      reason: 'Chart is not signed : Signature verification not required'
    - check: v1.0/contains-values
      type: Mandatory
      outcome: PASS
      reason: Values file exist
    - check: v1.0/has-readme
      type: Mandatory
      outcome: PASS
      reason: Chart has a README
    - check: v1.0/helm-lint
      type: Mandatory
      outcome: PASS
      reason: Helm lint successful
    - check: v1.1/images-are-certified
      type: Mandatory
      outcome: PASS
      reason: |-
        Image is Red Hat certified : ghcr.io/kubevault/vault-operator:v0.24.0-rc.0-ubi
        Image is Red Hat certified : ghcr.io/appscode/kubectl-nonroot:1.34-ubi

