{{- if .Values.tls.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.database_service_name }}-service-ca
  labels:
    template: valkey-persistent-template
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
data: {}
{{- end }}
