{{- $data := fromYaml (.Files.Get "data.yaml") -}}
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: dotnet
  annotations:
    openshift.io/display-name: .NET SDK
spec:
  tags:
  {{- $latestversion := $data.latestversion }}
  {{- $latest := index $data.releases $latestversion }}
  - name: latest
    annotations:
      openshift.io/display-name: .NET SDK (Latest)
      openshift.io/provider-display-name: Red Hat, Inc.
      description: |-
        Build and run applications using the latest .NET SDK. For more information about using this builder image, including OpenShift considerations, see {{ $latest.sdkdoc }}.

        WARNING: By selecting this tag, your application will automatically update to use the latest version of .NET available on OpenShift, including major version updates.
      iconClass: icon-dotnet
      tags: builder,dotnet,hidden
      supports: dotnet
      sampleRepo: https://github.com/redhat-developer/s2i-dotnetcore-ex
      sampleContextDir: app
      sampleRef: dotnet-{{ $latestversion }}
    from:
      kind: ImageStreamTag
      name: '{{ $latestversion }}'
    referencePolicy:
      type: Local
  {{- range $version, $info := $data.releases }}
  - name: {{ $version }}-{{ include "platformTag" $info.platform }}
    annotations:
      openshift.io/display-name: .NET SDK {{ $version }} ({{ $info.platform }})
      openshift.io/provider-display-name: Red Hat, Inc.
      description: Build and run .NET {{ $version }} applications on {{ $info.platform }}. For more information
        about using this builder image, including OpenShift considerations, see {{ $info.sdkdoc }}.
      iconClass: icon-dotnet
      tags: builder,dotnet,hidden
      version: '{{ $version }}'
      supports: dotnet,dotnet:{{ $version }}
      sampleRepo: https://github.com/redhat-developer/s2i-dotnetcore-ex
      sampleContextDir: app
      sampleRef: dotnet-{{ $version }}
    from:
      kind: DockerImage
      name: {{ $info.sdkrepository }}
    referencePolicy:
      type: Local
  - name: '{{ $version }}'
    annotations:
      openshift.io/display-name: .NET SDK {{ $version }} ({{ $info.platform }})
      openshift.io/provider-display-name: Red Hat, Inc.
      description: Build and run .NET {{ $version }} applications on {{ $info.platform }}. For more information
        about using this builder image, including OpenShift considerations, see {{ $info.sdkdoc }}.
      iconClass: icon-dotnet
      tags: builder,dotnet
      version: '{{ $version }}'
      supports: dotnet,dotnet:{{ $version }}
      sampleRepo: https://github.com/redhat-developer/s2i-dotnetcore-ex
      sampleContextDir: app
      sampleRef: dotnet-{{ $version }}
    from:
      kind: DockerImage
      name: {{ $info.sdkrepository }}
    referencePolicy:
      type: Local
  {{- end }}