{{- if and .Values.cnpg.enabled .Values.cnpg.secrets.create (not .Values.cnpg.secrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: pg-emu-user-secret
  namespace: {{ include "tokenvisor.namespace" . }}
  labels:
    {{- include "tokenvisor.labels" . | nindent 4 }}
    app: cnpg

type: kubernetes.io/basic-auth
stringData:
{{- range $key, $value := .Values.cnpg.secrets.data }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
