{{- if and .Values.features.core .Values.emu.enabled .Values.emu.secret.create (not .Values.emu.secret.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: emu-secret
  namespace: {{ include "tokenvisor.namespace" . }}
  labels:
    {{- include "tokenvisor.labels" . | nindent 4 }}
    app: emu
    app.kubernetes.io/part-of: emu-backend

type: Opaque
stringData:
{{- range $key, $value := .Values.emu.secret.data }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
