{{- if and .Values.features.core .Values.studio.enabled .Values.studio.secret.create (not .Values.studio.secret.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: studio-secret
  namespace: {{ include "tokenvisor.namespace" . }}
  labels:
    {{- include "tokenvisor.labels" . | nindent 4 }}
    app: studio

type: Opaque
stringData:
{{- range $key, $value := .Values.studio.secret.data }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
