{{- if and .Values.victoriametrics.enabled .Values.victoriametrics.vmuser.create (not .Values.victoriametrics.vmuser.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: vmuser-secret
  namespace: {{ include "tokenvisor.namespace" . }}
  labels:
    {{- include "tokenvisor.labels" . | nindent 4 }}
    app: victoria-metrics

type: Opaque
stringData:
  password: {{ .Values.victoriametrics.vmuser.password | quote }}
{{- end }}
