apiVersion: v2
name: orion-ld
version: 1.0.3
appVersion: 1.0.1
kubeVersion: '>= 1.19'
home: https://github.com/FIWARE/context.Orion-LD
description: A Helm chart for running the fiware orion-ld context broker on kubernetes.
icon: https://fiware.github.io/catalogue/img/fiware.png
keywords:
- fiware
- orion-ld
sources:
- https://github.com/FIWARE/context.Orion-LD
maintainers:
- name: wistefan
  email: stefan.wiedemann@fiware.org
annotations:
  charts.openshift.io/name: orion-ld