apiversion: v1
kind: verify-report
metadata:
    tool:
        verifier-version: 1.6.0
        profile:
            VendorType: partner
            version: v1.1
        chart-uri: https://europe-docker.pkg.dev/nfv-ri/rh-helm-charts/nfvri
        digests:
            chart: sha256:590d7a20414c751498c355163f48bf312481726fc617f9a034bbcd682e802477
            package: 311b83691f68272f4cc09a13c547b67052457d02775b2455687c1b59f660b3b9
        lastCertifiedTimestamp: "2022-04-20T10:33:50.894848+00:00"
        testedOpenShiftVersion: "4.10"
        supportedOpenShiftVersions: '>=4.7'
        providerControlledDelivery: false
    chart:
        name: nfvri
        home: ""
        sources: []
        version: 4.3.0
        description: A Helm chart for Kubernetes to deploy the NFV-RI stack
        keywords: []
        maintainers: []
        icon: ""
        apiversion: v2
        condition: ""
        tags: ""
        appversion: 4.3.0
        deprecated: false
        annotations:
            charts.openshift.io/name: nfvri
        kubeversion: '>= 1.20.0'
        dependencies:
            - name: nfvri-agent
              version: 4.3.0
              repository: file://../nfvri-agent
              condition: ""
              tags: []
              enabled: false
              importvalues: []
              alias: ""
            - name: nfvri-apiserver
              version: 4.3.0
              repository: file://../nfvri-apiserver
              condition: ""
              tags: []
              enabled: false
              importvalues: []
              alias: ""
            - name: nfvri-orchestrator
              version: 4.3.0
              repository: file://../nfvri-orchestrator
              condition: ""
              tags: []
              enabled: false
              importvalues: []
              alias: ""
            - name: nfvri-dashboard
              version: 4.3.0
              repository: file://../nfvri-dashboard
              condition: ""
              tags: []
              enabled: false
              importvalues: []
              alias: ""
        type: application
    chart-overrides: ""
results:
    - check: v1.0/contains-test
      type: Mandatory
      outcome: PASS
      reason: Chart test files exist
    - check: v1.1/has-kubeversion
      type: Mandatory
      outcome: PASS
      reason: Kubernetes version specified
    - check: v1.0/not-contains-crds
      type: Mandatory
      outcome: PASS
      reason: Chart does not contain CRDs
    - check: v1.0/images-are-certified
      type: Mandatory
      outcome: FAIL
      reason: |-
        Image is not Red Hat certified : docker.io/bitnami/redis:6.2.6-debian-10-r169 : No images found for Registry/Repository: docker.io/bitnami/redis
        Image is not Red Hat certified : busybox : Respository not found: busybox
        Image is Red Hat certified : europe-docker.pkg.dev/nfv-ri/images/dc-agent-rhel8:v4.3.0
        Image is Red Hat certified : europe-docker.pkg.dev/nfv-ri/images/apiserver-ubi8:v4.3.0
        Image is Red Hat certified : europe-docker.pkg.dev/nfv-ri/images/dashboard-ubi8:v4.3.0
        Image is Red Hat certified : europe-docker.pkg.dev/nfv-ri/images/orchestrator-rhel8:v4.3.0
        Image is not Red Hat certified : docker.io/bitnami/postgresql:10 : No images found for Registry/Repository: docker.io/bitnami/postgresql
    - check: v1.0/helm-lint
      type: Mandatory
      outcome: PASS
      reason: Helm lint successful
    - check: v1.0/chart-testing
      type: Mandatory
      outcome: PASS
      reason: Chart tests have passed
    - check: v1.0/is-helm-v3
      type: Mandatory
      outcome: PASS
      reason: API version is V2, used in Helm 3
    - check: v1.0/contains-values
      type: Mandatory
      outcome: PASS
      reason: Values file exist
    - check: v1.0/contains-values-schema
      type: Mandatory
      outcome: PASS
      reason: Values schema file exist
    - check: v1.0/not-contain-csi-objects
      type: Mandatory
      outcome: PASS
      reason: CSI objects do not exist
    - check: v1.0/required-annotations-present
      type: Mandatory
      outcome: PASS
      reason: All required annotations present
    - check: v1.0/has-readme
      type: Mandatory
      outcome: PASS
      reason: Chart has a README
