apiversion: v1
kind: verify-report
metadata:
    tool:
        verifier-version: 1.6.0
        profile:
            VendorType: partner
            version: v1.1
        chart-uri: https://europe-docker.pkg.dev/nfv-ri/helm-charts/nfvri
        digests:
            chart: sha256:7769f458780f95c4cdfc3ebbcc73494caf557abe44a3b9eb11c6d25b37f1b039
            package: f5f29e95246924332bbdd7fc6461c9973f990e1f6f82182f202dc7d6b5095582
        lastCertifiedTimestamp: "2022-04-21T10:50:04.068737+00:00"
        testedOpenShiftVersion: "4.10"
        supportedOpenShiftVersions: '>=4.7'
        providerControlledDelivery: false
    chart:
        name: nfvri
        home: ""
        sources: []
        version: 4.3.0
        description: A Helm chart for Kubernetes to deploy the NFV-RI stack
        keywords: []
        maintainers: []
        icon: ""
        apiversion: v2
        condition: ""
        tags: ""
        appversion: v4.3.0
        deprecated: false
        annotations:
            charts.openshift.io/name: nfvri
        kubeversion: '>= 1.20.0'
        dependencies:
            - name: nfvri-agent
              version: 4.3.0
              repository: file://../nfvri-agent
              condition: ""
              tags: []
              enabled: false
              importvalues: []
              alias: ""
            - name: nfvri-apiserver
              version: 4.3.0
              repository: file://../nfvri-apiserver
              condition: ""
              tags: []
              enabled: false
              importvalues: []
              alias: ""
            - name: nfvri-orchestrator
              version: 4.3.0
              repository: file://../nfvri-orchestrator
              condition: ""
              tags: []
              enabled: false
              importvalues: []
              alias: ""
            - name: nfvri-dashboard
              version: 4.3.0
              repository: file://../nfvri-dashboard
              condition: ""
              tags: []
              enabled: false
              importvalues: []
              alias: ""
        type: application
    chart-overrides: ""
results:
    - check: v1.0/is-helm-v3
      type: Mandatory
      outcome: PASS
      reason: API version is V2, used in Helm 3
    - check: v1.1/has-kubeversion
      type: Mandatory
      outcome: PASS
      reason: Kubernetes version specified
    - check: v1.0/required-annotations-present
      type: Mandatory
      outcome: PASS
      reason: All required annotations present
    - check: v1.0/not-contains-crds
      type: Mandatory
      outcome: PASS
      reason: Chart does not contain CRDs
    - check: v1.0/helm-lint
      type: Mandatory
      outcome: PASS
      reason: Helm lint successful
    - check: v1.0/not-contain-csi-objects
      type: Mandatory
      outcome: PASS
      reason: CSI objects do not exist
    - check: v1.0/images-are-certified
      type: Mandatory
      outcome: PASS
      reason: |-
        Image is Red Hat certified : europe-docker.pkg.dev/nfv-ri/images/dc-agent-rhel8:v4.3.0
        Image is Red Hat certified : europe-docker.pkg.dev/nfv-ri/images/apiserver-ubi8:v4.3.0
        Image is Red Hat certified : europe-docker.pkg.dev/nfv-ri/images/dashboard-ubi8:v4.3.0
        Image is Red Hat certified : europe-docker.pkg.dev/nfv-ri/images/orchestrator-rhel8:v4.3.0
        Image is Red Hat certified : registry.access.redhat.com/ubi8/ubi:8.4-206
    - check: v1.0/has-readme
      type: Mandatory
      outcome: PASS
      reason: Chart has a README
    - check: v1.0/contains-test
      type: Mandatory
      outcome: PASS
      reason: Chart test files exist
    - check: v1.0/contains-values
      type: Mandatory
      outcome: PASS
      reason: Values file exist
    - check: v1.0/contains-values-schema
      type: Mandatory
      outcome: PASS
      reason: Values schema file exist
    - check: v1.0/chart-testing
      type: Mandatory
      outcome: PASS
      reason: Chart tests have passed
