apiversion: v1
kind: verify-report
metadata:
    tool:
        verifier-version: 1.13.12
        profile:
            VendorType: partner
            version: v1.3
        reportDigest: uint64:16815478814945506975
        chart-uri: N/A
        digests:
            chart: sha256:927de9ccfe91d02556edec97aa971ed3f9c3d6c8342b332e1733e5c51ecf6588
            package: 990b359e6681f8fd88b7681b4ee290706f23645022ca3c35e15d2567de0ca072
        lastCertifiedTimestamp: "2025-08-25T13:02:13.10221+00:00"
        testedOpenShiftVersion: "4.14"
        supportedOpenShiftVersions: '>=4.1'
        webCatalogOnly: true
    chart:
        name: nonamesec-ubi
        home: ""
        sources: []
        version: 3.46.16-lts
        description: Noname Helm on k8s
        keywords: []
        maintainers: []
        icon: ""
        apiversion: v2
        condition: ""
        tags: ""
        appversion: 3.46.16-lts
        deprecated: false
        annotations:
            charts.openshift.io/name: Remote Engine
        kubeversion: '>=1.0.0-0'
        dependencies:
            - name: noname
              version: 0.1.0
              repository: file://charts/noname
              condition: global.noname.enabled
              tags: []
              enabled: false
              importvalues: []
              alias: ""
            - name: engine
              version: 0.1.0
              repository: file://charts/engine
              condition: global.engine.enabled
              tags: []
              enabled: false
              importvalues: []
              alias: ""
            - name: active
              version: 0.1.0
              repository: file://charts/active
              condition: global.active.enabled
              tags: []
              enabled: false
              importvalues: []
              alias: ""
            - name: platform
              version: 0.1.0
              repository: file://charts/platform
              condition: global.platform.enabled
              tags: []
              enabled: false
              importvalues: []
              alias: ""
            - name: router
              version: 0.1.0
              repository: file://charts/router
              condition: global.router.enabled
              tags: []
              enabled: false
              importvalues: []
              alias: ""
            - name: noagentapi
              version: 0.1.0
              repository: file://charts/noagentapi
              condition: noagentapi.enabled
              tags: []
              enabled: false
              importvalues: []
              alias: ""
            - name: rabbitmq
              version: 15.3.3
              repository: file://charts/rabbitmq
              condition: global.noname.enabled,global.rabbitmq.enabled
              tags: []
              enabled: false
              importvalues: []
              alias: ""
            - name: nns-eso
              version: 0.1.0
              repository: file://charts/nns-eso
              condition: global.nns_eso.enabled
              tags: []
              enabled: false
              importvalues: []
              alias: ""
        type: ""
    chart-overrides: ""
results:
    - check: v1.1/images-are-certified
      type: Mandatory
      outcome: PASS
      reason: |-
        Image is Red Hat certified : us-central1-docker.pkg.dev/noname-artifacts/nns-docker/nats-jetstream:2.10.24-custom-ubi
        Image is Red Hat certified : us-central1-docker.pkg.dev/noname-artifacts/nns-docker/cloud-metadata:v3.46.16-lts-ubi
        Image is Red Hat certified : us-central1-docker.pkg.dev/noname-artifacts/nns-docker/heavy-engine:v3.46.16-lts-ubi
        Image is Red Hat certified : us-central1-docker.pkg.dev/noname-artifacts/nns-docker/integrations-adapter:v3.46.16-lts-ubi
        Image is Red Hat certified : us-central1-docker.pkg.dev/noname-artifacts/nns-docker/nogate:v3.46.16-lts-ubi
        Image is Red Hat certified : us-central1-docker.pkg.dev/noname-artifacts/nns-docker/platform-integrations:v3.46.16-lts-ubi
        Image is Red Hat certified : us-central1-docker.pkg.dev/noname-artifacts/nns-docker/rhel8/postgresql-15:1-66.1716485364
        Image is Red Hat certified : us-central1-docker.pkg.dev/noname-artifacts/nns-docker/nginx:v3.46.16-lts-ubi
        Image is Red Hat certified : us-central1-docker.pkg.dev/noname-artifacts/nns-docker/light-engine:v3.46.16-lts-ubi
        Image is Red Hat certified : us-central1-docker.pkg.dev/noname-artifacts/nns-docker/router:v3.46.16-lts-ubi
    - check: v1.0/is-helm-v3
      type: Mandatory
      outcome: PASS
      reason: API version is V2, used in Helm 3
    - check: v1.0/signature-is-valid
      type: Mandatory
      outcome: SKIPPED
      reason: 'Chart is not signed : Signature verification not required'
    - check: v1.0/required-annotations-present
      type: Mandatory
      outcome: PASS
      reason: All required annotations present
    - check: v1.0/chart-testing
      type: Mandatory
      outcome: PASS
      reason: Chart tests have passed
    - check: v1.0/has-notes
      type: Optional
      outcome: PASS
      reason: Chart does contain NOTES.txt
    - check: v1.0/has-readme
      type: Mandatory
      outcome: PASS
      reason: Chart has a README
    - check: v1.0/contains-values
      type: Mandatory
      outcome: PASS
      reason: Values file exist
    - check: v1.0/contains-values-schema
      type: Mandatory
      outcome: PASS
      reason: Values schema file exist
    - check: v1.1/has-kubeversion
      type: Mandatory
      outcome: PASS
      reason: Kubernetes version specified
    - check: v1.0/contains-test
      type: Mandatory
      outcome: PASS
      reason: Chart test files exist
    - check: v1.0/not-contains-crds
      type: Mandatory
      outcome: PASS
      reason: Chart does not contain CRDs
    - check: v1.0/not-contain-csi-objects
      type: Mandatory
      outcome: PASS
      reason: CSI objects do not exist
    - check: v1.0/helm-lint
      type: Mandatory
      outcome: PASS
      reason: Helm lint successful
