apiversion: v1
kind: verify-report
metadata:
    tool:
        verifier-version: 1.13.13
        profile:
            VendorType: redhat
            version: v1.3
        reportDigest: uint64:16174956400039881922
        chart-uri: /charts/redhat-rhem-1.0.2.tgz
        digests:
            chart: sha256:33ec6fc283909126577ffab667fa53b6c1cc65a456cefec42223e0528848f809
            package: 6407c0f094998bd1764784d2f40cd4cb114af4e084c94a9cce5b148710114fc0
        lastCertifiedTimestamp: "2026-01-13T21:50:01.681745+00:00"
        testedOpenShiftVersion: 4.20.8
        supportedOpenShiftVersions: '>=4.18'
        webCatalogOnly: false
    chart:
        name: redhat-rhem
        home: https://red.ht/rhem
        sources: []
        version: 1.0.2
        description: A helm chart for Red Hat Edge Manager
        keywords: []
        maintainers: []
        icon: data:image/svg+xml;base64,PHN2ZyBlbmFibGUtYmFja2dyb3VuZD0ibmV3IDAgMCAxMDAgMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDEwMCAxMDAiIHdpZHRoPSIxMDAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHBhdGggZD0ibTY2LjcgNTUuOGM2LjYgMCAxNi4xLTEuNCAxNi4xLTkuMiAwLS42IDAtMS4yLS4yLTEuOGwtMy45LTE3Yy0uOS0zLjctMS43LTUuNC04LjMtOC43LTUuMS0yLjYtMTYuMi02LjktMTkuNS02LjktMy4xIDAtNCA0LTcuNiA0LTMuNSAwLTYuMS0yLjktOS40LTIuOS0zLjIgMC01LjIgMi4xLTYuOCA2LjYgMCAwLTQuNCAxMi41LTUgMTQuMy0uMS4zLS4xLjctLjEgMSAuMSA0LjcgMTkuMiAyMC42IDQ0LjcgMjAuNm0xNy4xLTZjLjkgNC4zLjkgNC44LjkgNS4zIDAgNy40LTguMyAxMS40LTE5LjEgMTEuNC0yNC42IDAtNDYuMS0xNC40LTQ2LjEtMjMuOSAwLTEuMy4zLTIuNi44LTMuOS04LjkuNS0yMC4zIDIuMS0yMC4zIDEyLjIgMCAxNi41IDM5LjIgMzYuOSA3MC4yIDM2LjkgMjMuOCAwIDI5LjgtMTAuNyAyOS44LTE5LjIgMC02LjctNS44LTE0LjMtMTYuMi0xOC44IiBmaWxsPSIjZWQxYzI0Ii8+PHBhdGggZD0ibTgzLjggNDkuOGMuOSA0LjMuOSA0LjguOSA1LjMgMCA3LjQtOC4zIDExLjQtMTkuMSAxMS40LTI0LjYgMC00Ni4xLTE0LjQtNDYuMS0yMy45IDAtMS4zLjMtMi42LjgtMy45bDEuOS00LjhjLS4xLjMtLjEuNy0uMSAxIDAgNC44IDE5LjEgMjAuNyA0NC43IDIwLjcgNi42IDAgMTYuMS0xLjQgMTYuMS05LjIgMC0uNiAwLTEuMi0uMi0xLjh6IiBmaWxsPSIjMDEwMTAxIi8+PC9zdmc+
        apiversion: v2
        condition: ""
        tags: ""
        appversion: 1.0.2
        deprecated: false
        annotations:
            charts.openshift.io/archs: x86_64
            charts.openshift.io/name: Red Hat Edge Manager
            charts.openshift.io/provider: Red Hat
            charts.openshift.io/supportURL: https://access.redhat.com/support
        kubeversion: '>= 1.31.0-0'
        dependencies: []
        type: application
    chart-overrides: ""
results:
    - check: v1.0/signature-is-valid
      type: Mandatory
      outcome: SKIPPED
      reason: 'Chart is not signed : Signature verification not required'
    - check: v1.0/has-readme
      type: Mandatory
      outcome: PASS
      reason: Chart has a README
    - check: v1.1/images-are-certified
      type: Mandatory
      outcome: PASS
      reason: |-
        Image certification skipped : registry.redhat.io/rhem/flightctl-db-setup-rhel9:1.0.2
        Image certification skipped : registry.redhat.io/rhem/flightctl-alert-exporter-rhel9:1.0.2
        Image certification skipped : registry.redhat.io/rhem/flightctl-alertmanager-proxy-rhel9:1.0.2
        Image certification skipped : registry.redhat.io/rhem/flightctl-api-rhel9:1.0.2
        Image certification skipped : registry.redhat.io/rhem/flightctl-cli-artifacts-rhel9:1.0.2
        Image certification skipped : registry.redhat.io/rhem/flightctl-periodic-rhel9:1.0.2
        Image certification skipped : registry.redhat.io/rhem/flightctl-telemetry-gateway-rhel9:1.0.2
        Image certification skipped : registry.redhat.io/rhem/flightctl-worker-rhel9:1.0.2
        Image certification skipped : registry.redhat.io/openshift4/ose-cli-rhel9:v4.20.0
        Image is Red Hat certified : registry.access.redhat.com/ubi9/ubi-minimal:9.7-1763362218
        Image certification skipped : registry.redhat.io/rhel9/postgresql-16:9.6-1752571367
        Image certification skipped : registry.redhat.io/rhel9/redis-7:9.6-1752567986
        Image certification skipped : registry.redhat.io/rhem/flightctl-ui-rhel9:1.0.2
        Image certification skipped : registry.redhat.io/rhacm2/prometheus-alertmanager-rhel9:v2.13.2
    - check: v1.0/not-contain-csi-objects
      type: Mandatory
      outcome: PASS
      reason: CSI objects do not exist
    - check: v1.0/required-annotations-present
      type: Mandatory
      outcome: PASS
      reason: All required annotations present
    - check: v1.0/contains-values
      type: Mandatory
      outcome: PASS
      reason: Values file exist
    - check: v1.0/helm-lint
      type: Mandatory
      outcome: PASS
      reason: Helm lint successful
    - check: v1.0/not-contains-crds
      type: Mandatory
      outcome: PASS
      reason: Chart does not contain CRDs
    - check: v1.0/contains-test
      type: Mandatory
      outcome: PASS
      reason: Chart test files exist
    - check: v1.0/contains-values-schema
      type: Mandatory
      outcome: PASS
      reason: Values schema file exist
    - check: v1.1/has-kubeversion
      type: Mandatory
      outcome: PASS
      reason: Kubernetes version specified
    - check: v1.0/is-helm-v3
      type: Mandatory
      outcome: PASS
      reason: API version is V2, used in Helm 3
    - check: v1.0/chart-testing
      type: Mandatory
      outcome: PASS
      reason: Chart tests have passed
    - check: v1.0/has-notes
      type: Optional
      outcome: PASS
      reason: Chart does contain NOTES.txt

