Using config file: config.yaml
apiversion: v1
kind: verify-report
metadata:
    tool:
        verifier-version: 1.13.13
        profile:
            VendorType: partner
            version: v1.3
        reportDigest: uint64:10779734682327691868
        chart-uri: N/A
        digests:
            chart: sha256:b0c0e6e65ffe7673c13018e562683edecc8629c3bda6c332af5b155034b763db
            package: 082a220771ab8011b5cdd30570d3c221539afe442494f203e149bd9cf10d853e
        lastCertifiedTimestamp: "2025-12-04T15:12:47.999954+00:00"
        testedOpenShiftVersion: "4.20"
        supportedOpenShiftVersions: '>=4.8'
        webCatalogOnly: true
    chart:
        name: cmm-operator-k8s
        home: ""
        sources: []
        version: 25.11.0-p1
        description: A Helm chart for CMM in Kubernetes using operators
        keywords: []
        maintainers: []
        icon: https://www.nokia.com/chart-icon.png
        apiversion: v2
        condition: ""
        tags: ""
        appversion: ""
        deprecated: false
        annotations:
            charts.openshift.io/archs: x86_64
            charts.openshift.io/name: Nokia CMM
            charts.openshift.io/provider: Nokia
            charts.openshift.io/supportURL: https://github.com/nokiacmm/helm-chart
        kubeversion: '>= 1.21.0-0'
        dependencies: []
        type: application
    chart-overrides: ""
results:
    - check: v1.0/has-readme
      type: Mandatory
      outcome: PASS
      reason: Chart has a README
    - check: v1.0/helm-lint
      type: Mandatory
      outcome: PASS
      reason: Helm lint successful
    - check: v1.1/images-are-certified
      type: Mandatory
      outcome: PASS
      reason: 'Image is Red Hat certified : quay.io/nepravee/cmm-operator:CMM25.11.0.0'
    - check: v1.0/is-helm-v3
      type: Mandatory
      outcome: PASS
      reason: API version is V2, used in Helm 3
    - check: v1.0/not-contain-csi-objects
      type: Mandatory
      outcome: PASS
      reason: CSI objects do not exist
    - check: v1.0/required-annotations-present
      type: Mandatory
      outcome: PASS
      reason: All required annotations present
    - check: v1.0/signature-is-valid
      type: Mandatory
      outcome: SKIPPED
      reason: 'Chart is not signed : Signature verification not required'
    - check: v1.0/chart-testing
      type: Mandatory
      outcome: PASS
      reason: Chart tests have passed
    - check: v1.0/contains-values-schema
      type: Mandatory
      outcome: PASS
      reason: Values schema file exist
    - check: v1.0/contains-values
      type: Mandatory
      outcome: PASS
      reason: Values file exist
    - check: v1.0/has-notes
      type: Optional
      outcome: PASS
      reason: Chart does contain NOTES.txt
    - check: v1.1/has-kubeversion
      type: Mandatory
      outcome: PASS
      reason: Kubernetes version specified
    - check: v1.0/not-contains-crds
      type: Mandatory
      outcome: PASS
      reason: Chart does not contain CRDs
    - check: v1.0/contains-test
      type: Mandatory
      outcome: PASS
      reason: Chart test files exist

