{{- if not (.Values.clusterRole.readOnly | default false) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wave-autoscale-crb-edit
  namespace: {{ if eq .Release.Namespace "default" }}{{ .Values.default_namespace }}{{ else }}{{ .Release.Namespace }}{{ end }}
subjects:
  - kind: ServiceAccount
    name: wave-autoscale-sa
    namespace: {{ if eq .Release.Namespace "default" }}{{ .Values.default_namespace }}{{ else }}{{ .Release.Namespace }}{{ end }}
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wave-autoscale-cr-pv-pvc-edit
  namespace: {{ if eq .Release.Namespace "default" }}{{ .Values.default_namespace }}{{ else }}{{ .Release.Namespace }}{{ end }}
rules:
  - apiGroups: [ "" ]
    resources: [ "persistentvolumes", "persistentvolumeclaims", "volumeattachments" ]
    verbs: [ "create", "update", "patch", "delete" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wave-autoscale-crb-pv-pvc-edit
  namespace: {{ if eq .Release.Namespace "default" }}{{ .Values.default_namespace }}{{ else }}{{ .Release.Namespace }}{{ end }}
subjects:
  - kind: ServiceAccount
    name: wave-autoscale-sa
    namespace: {{ if eq .Release.Namespace "default" }}{{ .Values.default_namespace }}{{ else }}{{ .Release.Namespace }}{{ end }}
roleRef:
  kind: ClusterRole
  name: wave-autoscale-cr-pv-pvc-edit
  apiGroup: rbac.authorization.k8s.io
---
{{ end }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wave-autoscale-crb-view
  namespace: {{ if eq .Release.Namespace "default" }}{{ .Values.default_namespace }}{{ else }}{{ .Release.Namespace }}{{ end }}
subjects:
  - kind: ServiceAccount
    name: wave-autoscale-sa
    namespace: {{ if eq .Release.Namespace "default" }}{{ .Values.default_namespace }}{{ else }}{{ .Release.Namespace }}{{ end }}
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wave-autoscale-cr-nodes-read
  namespace: {{ if eq .Release.Namespace "default" }}{{ .Values.default_namespace }}{{ else }}{{ .Release.Namespace }}{{ end }}
rules:
  - apiGroups: [ "" ]
    resources: [ "nodes" ]
    verbs: [ "get", "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wave-autoscale-crb-nodes-read
  namespace: {{ if eq .Release.Namespace "default" }}{{ .Values.default_namespace }}{{ else }}{{ .Release.Namespace }}{{ end }}
subjects:
  - kind: ServiceAccount
    name: wave-autoscale-sa
    namespace: {{ if eq .Release.Namespace "default" }}{{ .Values.default_namespace }}{{ else }}{{ .Release.Namespace }}{{ end }}
roleRef:
  kind: ClusterRole
  name: wave-autoscale-cr-nodes-read
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wave-autoscale-cr-pv-pvc-read
  namespace: {{ if eq .Release.Namespace "default" }}{{ .Values.default_namespace }}{{ else }}{{ .Release.Namespace }}{{ end }}
rules:
  - apiGroups: [ "" ]
    resources: [ "persistentvolumes", "persistentvolumeclaims" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "storage.k8s.io" ]
    resources: [ "volumeattachments", "storageclasses" ]
    verbs: [ "get", "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wave-autoscale-crb-pv-pvc-read
  namespace: {{ if eq .Release.Namespace "default" }}{{ .Values.default_namespace }}{{ else }}{{ .Release.Namespace }}{{ end }}
subjects:
  - kind: ServiceAccount
    name: wave-autoscale-sa
    namespace: {{ if eq .Release.Namespace "default" }}{{ .Values.default_namespace }}{{ else }}{{ .Release.Namespace }}{{ end }}
roleRef:
  kind: ClusterRole
  name: wave-autoscale-cr-pv-pvc-read
  apiGroup: rbac.authorization.k8s.io
---
{{- if .Values.clusterRole.istioAdmin | default false }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wave-autoscale-cr-istio-admin
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
  - apiGroups: [ "config.istio.io", "networking.istio.io", "rbac.istio.io", "authentication.istio.io", "security.istio.io", "extensions.istio.io" ]
    resources: [ "*" ]
    verbs: [ "*" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wave-autoscale-crb-istio-admin
  namespace: {{ if eq .Release.Namespace "default" }}{{ .Values.default_namespace }}{{ else }}{{ .Release.Namespace }}{{ end }}
subjects:
  - kind: ServiceAccount
    name: wave-autoscale-sa
    namespace: {{ if eq .Release.Namespace "default" }}{{ .Values.default_namespace }}{{ else }}{{ .Release.Namespace }}{{ end }}
roleRef:
  kind: ClusterRole
  name: wave-autoscale-cr-istio-admin
  apiGroup: rbac.authorization.k8s.io
---
{{ end }}
