{{- if .Values.spec.agent.enabled | default true }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wave-autoscale-agent-sa
  namespace: {{ if eq .Release.Namespace "default" }}{{ .Values.default_namespace }}{{ else }}{{ .Release.Namespace }}{{ end }}
  {{- with .Values.serviceAccountAgent.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{ end }}