apiversion: v1
kind: verify-report
metadata:
    tool:
        verifier-version: 1.13.14
        profile:
            VendorType: partner
            version: v1.3
        reportDigest: uint64:12170238457280087874
        chart-uri: .
        digests:
            chart: sha256:d9ad29d2d60038365c3dcbff262ab3d692159957f892b3996fa8825a8dcde25f
        lastCertifiedTimestamp: "2026-01-16T09:36:28.220226+08:00"
        testedOpenShiftVersion: "4.20"
        supportedOpenShiftVersions: '>=4.8'
        webCatalogOnly: false
    chart:
        name: tokenvisor
        home: ""
        sources: []
        version: 0.1.0
        description: TokenVisor Helm chart (operators required as pre-requisites)
        keywords: []
        maintainers: []
        icon: ""
        apiversion: v2
        condition: ""
        tags: ""
        appversion: 0.0.0
        deprecated: false
        annotations:
            charts.openshift.io/name: TokenVisor
        kubeversion: '>=1.21.0-0'
        dependencies:
            - name: victoria-logs-single
              version: 0.11.19
              repository: https://victoriametrics.github.io/helm-charts/
        type: application
    chart-overrides: ""
results:
    - check: v1.0/has-readme
      type: Mandatory
      outcome: PASS
      reason: Chart has a README
    - check: v1.0/not-contains-crds
      type: Mandatory
      outcome: PASS
      reason: Chart does not contain CRDs
    - check: v1.0/contains-test
      type: Mandatory
      outcome: PASS
      reason: Chart test files exist
    - check: v1.0/contains-values-schema
      type: Mandatory
      outcome: PASS
      reason: Values schema file exist
    - check: v1.0/required-annotations-present
      type: Mandatory
      outcome: PASS
      reason: All required annotations present
    - check: v1.0/chart-testing
      type: Mandatory
      outcome: PASS
      reason: Chart tests have passed
    - check: v1.0/has-notes
      type: Optional
      outcome: PASS
      reason: Chart does contain NOTES.txt
    - check: v1.0/helm-lint
      type: Mandatory
      outcome: PASS
      reason: Helm lint successful
    - check: v1.1/images-are-certified
      type: Mandatory
      outcome: PASS
      reason: |-
        Image is Red Hat certified : ghcr.io/embeddedllm/tokenvisor/postgres-17-ubi:17.7
        Image is Red Hat certified : ghcr.io/embeddedllm/tokenvisor-curl-ubi:8.12.1
        Image is Red Hat certified : ghcr.io/embeddedllm/jamaibase/otelcol-openshift:20250107
        Image is Red Hat certified : ghcr.io/embeddedllm/jamaibase/clickhouse-client-openshift:25.12.2.54
        Image is Red Hat certified : ghcr.io/embeddedllm/jamaibase/clickhouse-server-openshift:25.12.2.54
        Image is Red Hat certified : ghcr.io/embeddedllm/jamaibase/clickhouse-keeper-openshift:24.12.6.70
        Image is Red Hat certified : ghcr.io/embeddedllm/tokenvisor/tokenvisor-emu-openshift:20251229
        Image is Red Hat certified : ghcr.io/embeddedllm/tokenvisor/tokenvisor-studio-openshift:20260113
        Image is Red Hat certified : ghcr.io/embeddedllm/tokenvisor/victoria-logs-ubi:v1.41.1
    - check: v1.0/not-contain-csi-objects
      type: Mandatory
      outcome: PASS
      reason: CSI objects do not exist
    - check: v1.0/contains-values
      type: Mandatory
      outcome: PASS
      reason: Values file exist
    - check: v1.0/is-helm-v3
      type: Mandatory
      outcome: PASS
      reason: API version is V2, used in Helm 3
    - check: v1.0/signature-is-valid
      type: Mandatory
      outcome: SKIPPED
      reason: 'Chart is not signed : Signature verification not required'
    - check: v1.1/has-kubeversion
      type: Mandatory
      outcome: PASS
      reason: Kubernetes version specified
