apiversion: v1
kind: verify-report
metadata:
    tool:
        verifier-version: 1.13.14
        profile:
            VendorType: partner
            version: v1.3
        reportDigest: uint64:6324960314039484105
        chart-uri: wave-autoscale-helm-3.0.1.tgz
        digests:
            chart: sha256:35f41c5f9c2ea1163ab8ccfea7a0ae42e92dd6ac2256d0cbc72ce4d32ffa4e2b
            package: 20eb0041e5f195fdc4da47f65367472e894e8cb05d6c152e49270ad50100bb36
        lastCertifiedTimestamp: "2026-01-15T16:16:46.02614+09:00"
        testedOpenShiftVersion: "4.18"
        supportedOpenShiftVersions: '>=4.13'
        webCatalogOnly: false
    chart:
        name: wave-autoscale-helm
        home: https://waveautoscale.com
        sources: []
        version: 3.0.1
        description: AI-powered Kubernetes resource optimization and cost reduction solution
        keywords:
            - autoscaling
            - kubernetes
            - cost-optimization
            - machine-learning
            - resource-management
            - openshift
        maintainers:
            - name: STCLab Inc.
              email: team@waveautoscale.com
              url: ""
        icon: https://waveautoscale.com/wa-logo-text.svg
        apiversion: v2
        condition: ""
        tags: ""
        appversion: 3.0.1
        deprecated: false
        annotations:
            charts.openshift.io/name: wave-autoscale
            charts.openshift.io/supportedOpenShiftVersions: '>=4.13'
        kubeversion: '>= 1.26.0-0'
        dependencies: []
        type: application
    chart-overrides: ""
results:
    - check: v1.1/has-kubeversion
      type: Mandatory
      outcome: PASS
      reason: Kubernetes version specified
    - check: v1.1/images-are-certified
      type: Mandatory
      outcome: PASS
      reason: |-
        Image is Red Hat certified : registry.connect.redhat.com/stclab-inc/wave-autoscale-cadvisor:v0.52.1-redhat
        Image is Red Hat certified : registry.connect.redhat.com/stclab-inc/wave-autoscale-core:3.0.1-redhat
        Image is Red Hat certified : registry.connect.redhat.com/stclab-inc/wave-autoscale-web-console:3.0.1-redhat
        Image is Red Hat certified : registry.connect.redhat.com/stclab-inc/wave-autoscale-intelligence:3.0.1-redhat
        Image is Red Hat certified : registry.access.redhat.com/ubi9/ubi-minimal:latest
        Image is Red Hat certified : registry.connect.redhat.com/stclab-inc/wave-autoscale-agent:3.0.1-redhat
    - check: v1.0/not-contains-crds
      type: Mandatory
      outcome: PASS
      reason: Chart does not contain CRDs
    - check: v1.0/has-notes
      type: Optional
      outcome: PASS
      reason: Chart does contain NOTES.txt
    - check: v1.0/is-helm-v3
      type: Mandatory
      outcome: PASS
      reason: API version is V2, used in Helm 3
    - check: v1.0/required-annotations-present
      type: Mandatory
      outcome: PASS
      reason: All required annotations present
    - check: v1.0/chart-testing
      type: Mandatory
      outcome: PASS
      reason: Chart tests have passed
    - check: v1.0/contains-values
      type: Mandatory
      outcome: PASS
      reason: Values file exist
    - check: v1.0/has-readme
      type: Mandatory
      outcome: PASS
      reason: Chart has a README
    - check: v1.0/helm-lint
      type: Mandatory
      outcome: PASS
      reason: Helm lint successful
    - check: v1.0/not-contain-csi-objects
      type: Mandatory
      outcome: PASS
      reason: CSI objects do not exist
    - check: v1.0/signature-is-valid
      type: Mandatory
      outcome: SKIPPED
      reason: 'Chart is not signed : Signature verification not required'
    - check: v1.0/contains-test
      type: Mandatory
      outcome: PASS
      reason: Chart test files exist
    - check: v1.0/contains-values-schema
      type: Mandatory
      outcome: PASS
      reason: Values schema file exist

