application_domain: "" # TODO: must define a default value for .application_domain
context_dir: "" # TODO: must define a default value for .context_dir
generic_webhook_secret: "FOO" # TODO: must define a default value for .generic_webhook_secret
github_webhook_secret: "SOMETHING"# TODO: must define a default value for .github_webhook_secret
memory_limit: 512Mi
name: nodejs-example
namespace: openshift
nodejs_version: 24-ubi10
npm_mirror: "" # TODO: must define a default value for .npm_mirror
source_repository_ref: "master" # TODO: must define a default value for .source_repository_ref
source_repository_url: https://github.com/sclorg/nodejs-ex.git
registry:
    enabled: false
    name: "quay.io"
    namespace: "something"
    push_secret: ""
