apiversion: v1
kind: verify-report
metadata:
    tool:
        verifier-version: 1.14.0
        profile:
            VendorType: partner
            version: v1.3
        reportDigest: uint64:2453383556695986641
        chart-uri: /charts/radware-akc-helm-1.8.0.tgz
        digests:
            chart: sha256:373ebea8b5558ad32326fa36cd607f1569d6ba231e77c78ed2486b0b9aed3852
            package: 6a8073f767c308c8adb5545da85f25adf025dc825787c77cf80b0c882ef58eb1
        lastCertifiedTimestamp: "2026-02-16T15:49:17.716712+00:00"
        testedOpenShiftVersion: "4.10"
        supportedOpenShiftVersions: '>=4.10'
        webCatalogOnly: false
    chart:
        name: radware-akc-helm
        home: ""
        sources: []
        version: 1.8.0
        description: The parent chart for Radware AKC
        keywords: []
        maintainers: []
        icon: https://www.radware.com/favicon.ico
        apiversion: v2
        condition: ""
        tags: ""
        appversion: 1.8.0
        deprecated: false
        annotations:
            charts.openshift.io/name: akc
        kubeversion: '>=1.23.0-0'
        dependencies:
            - name: controller
              version: 1.8.0
              repository: file://charts/controller
              condition: controller.enabled
            - name: aggregator
              version: 1.8.0
              repository: file://charts/aggregator
              condition: aggregator.enabled
            - name: configurator
              version: 1.8.0
              repository: file://charts/configurator
              condition: configurator.enabled
        type: application
    chart-overrides: ""
results:
    - check: v1.0/chart-testing
      type: Mandatory
      outcome: PASS
      reason: Chart tests have passed
    - check: v1.0/contains-test
      type: Mandatory
      outcome: PASS
      reason: Chart test files exist
    - check: v1.0/contains-values-schema
      type: Mandatory
      outcome: PASS
      reason: Values schema file exist
    - check: v1.0/contains-values
      type: Mandatory
      outcome: PASS
      reason: Values file exist
    - check: v1.0/has-readme
      type: Mandatory
      outcome: PASS
      reason: Chart has a README
    - check: v1.1/images-are-certified
      type: Mandatory
      outcome: PASS
      reason: |-
        Image is Red Hat certified : ghcr.io/rdwr-mohamedt/akc-controller:487
        Image is Red Hat certified : registry.access.redhat.com/ubi10/ubi-minimal:latest
    - check: v1.0/not-contain-csi-objects
      type: Mandatory
      outcome: PASS
      reason: CSI objects do not exist
    - check: v1.0/not-contains-crds
      type: Mandatory
      outcome: PASS
      reason: Chart does not contain CRDs
    - check: v1.0/signature-is-valid
      type: Mandatory
      outcome: SKIPPED
      reason: 'Chart is not signed : Signature verification not required'
    - check: v1.0/has-notes
      type: Optional
      outcome: PASS
      reason: Chart does contain NOTES.txt
    - check: v1.0/is-helm-v3
      type: Mandatory
      outcome: PASS
      reason: API version is V2, used in Helm 3
    - check: v1.1/has-kubeversion
      type: Mandatory
      outcome: PASS
      reason: Kubernetes version specified
    - check: v1.0/helm-lint
      type: Mandatory
      outcome: PASS
      reason: Helm lint successful
    - check: v1.0/required-annotations-present
      type: Mandatory
      outcome: PASS
      reason: All required annotations present

