apiversion: v1
kind: verify-report
metadata:
    tool:
        verifier-version: 1.12.2
        profile:
            VendorType: partner
            version: v1.2
        reportDigest: uint64:8663713546477886993
        chart-uri: N/A
        digests:
            chart: sha256:ff00196856540c0e5ce5653d7388605cd3d0772010aac23a2293f0672386849e
            package: 8d0ccd5fd2399ab6b26d817685de60ea3c300945039ba3de74ee9995b2109a5f
        lastCertifiedTimestamp: "2025-12-02T21:52:49.043759+00:00"
        testedOpenShiftVersion: 4.16.20
        supportedOpenShiftVersions: '>=4.8'
        webCatalogOnly: true
    chart:
        name: 5g-csdb-global
        home: ""
        sources: []
        version: 25.2.570-20250814.9942493
        description: A Helm chart for 5G Core cCSDB(25/08/14)
        keywords: []
        maintainers: []
        icon: ""
        apiversion: v2
        condition: ""
        tags: ""
        appversion: 25.B.0
        deprecated: false
        annotations:
            charts.openshift.io/archs: x86_64
            charts.openshift.io/name: 5g-csdb-global-25b
            charts.openshift.io/provider: Samsung Electronics
            charts.openshift.io/releaseDate: 25/08/14
            charts.openshift.io/supportURL: https://www.samsung.com/global/business/networks/contact-us/
        kubeversion: '>= 1.21.0-0'
        dependencies: []
        type: ""
    chart-overrides: ""
results:
    - check: v1.0/contains-values-schema
      type: Mandatory
      outcome: PASS
      reason: Values schema file exist
    - check: v1.1/images-are-certified
      type: Mandatory
      outcome: FAIL
      reason: |-
        Image is not Red Hat certified : quay.samsung.bos2.lab/samsung_5gc/global-nf-clbc:SVR25B_20250814_9942493
        Image is not Red Hat certified : quay.samsung.bos2.lab/samsung_5gc/global-nf-lem:SVR25B_20250814_9942493
        Image is not Red Hat certified : quay.samsung.bos2.lab/samsung_5gc/global-csdb-cdbm:SVR25B_20250814_9942493
        Image is not Red Hat certified : quay.samsung.bos2.lab/samsung_5gc/global-nf-lbm:SVR25B_20250814_9942493
        Image is not Red Hat certified : quay.samsung.bos2.lab/samsung_5gc/global-nf-pmexp:SVR25B_20250814_9942493
        Image is not Red Hat certified : quay.samsung.bos2.lab/samsung_5gc/global-csdb-ui:SVR25B_20250814_9942493
        Image is not Red Hat certified : quay.samsung.bos2.lab/samsung_5gc/global-nf-nsm:SVR25B_20250814_9942493
        Image is not Red Hat certified : quay.samsung.bos2.lab/samsung_5gc/global-nf-imim:SVR25B_20250814_9942493
        Image is not Red Hat certified : quay.samsung.bos2.lab/samsung_5gc/global-nf-utilbox:SVR25B_20250814_9942493
        Image is not Red Hat certified : quay.samsung.bos2.lab/samsung_5gc/global-nf-fm:SVR25B_20250814_9942493
        Image is not Red Hat certified : quay.samsung.bos2.lab/samsung_5gc/global-nf-dm:SVR25B_20250814_9942493
        Image is not Red Hat certified : quay.samsung.bos2.lab/samsung_5gc/global-csdb-pm:SVR25B_20250814_9942493
        Image is not Red Hat certified : quay.samsung.bos2.lab/samsung_5gc/global-nf-clbm:SVR25B_20250814_9942493
        Image is not Red Hat certified : quay.samsung.bos2.lab/samsung_5gc/global-nf-bgpm:SVR25B_20250814_9942493
        Image is not Red Hat certified : quay.samsung.bos2.lab/samsung_5gc/global-nf-imcm:SVR25B_20250814_9942493
        Image is not Red Hat certified : quay.samsung.bos2.lab/samsung_5gc/global-nf-ldbm:SVR25B_20250814_9942493
        Image is not Red Hat certified : quay.samsung.bos2.lab/samsung_5gc/global-csdb-vcdm:SVR25B_20250814_9942493
        Image is not Red Hat certified : quay.samsung.bos2.lab/samsung_5gc/global-nf-crm:SVR25B_20250814_9942493
        Image is not Red Hat certified : quay.samsung.bos2.lab/samsung_5gc/global-nf-bfdm:SVR25B_20250814_9942493
        Image is not Red Hat certified : quay.samsung.bos2.lab/samsung_5gc/global-nf-ima:SVR25B_20250814_9942493
        Image is not Red Hat certified : quay.samsung.bos2.lab/samsung_5gc/global-nf-cap:SVR25B_20250814_9942493
        Image is not Red Hat certified : quay.samsung.bos2.lab/samsung_5gc/global-nf-sshd:SVR25B_20250814_9942493
        Image is not Red Hat certified : quay.samsung.bos2.lab/samsung_5gc/global-nf-fqm:SVR25B_20250814_9942493
    - check: v1.1/has-kubeversion
      type: Mandatory
      outcome: PASS
      reason: Kubernetes version specified
    - check: v1.0/is-helm-v3
      type: Mandatory
      outcome: PASS
      reason: API version is V2, used in Helm 3
    - check: v1.0/not-contains-crds
      type: Mandatory
      outcome: PASS
      reason: Chart does not contain CRDs
    - check: v1.0/signature-is-valid
      type: Mandatory
      outcome: SKIPPED
      reason: 'Chart is not signed : Signature verification not required'
    - check: v1.0/contains-test
      type: Mandatory
      outcome: PASS
      reason: Chart test files exist
    - check: v1.0/contains-values
      type: Mandatory
      outcome: PASS
      reason: Values file exist
    - check: v1.0/not-contain-csi-objects
      type: Mandatory
      outcome: PASS
      reason: CSI objects do not exist
    - check: v1.0/required-annotations-present
      type: Mandatory
      outcome: PASS
      reason: All required annotations present
    - check: v1.0/has-readme
      type: Mandatory
      outcome: PASS
      reason: Chart has a README
    - check: v1.0/helm-lint
      type: Mandatory
      outcome: PASS
      reason: Helm lint successful
    - check: v1.0/chart-testing
      type: Mandatory
      outcome: PASS
      reason: Chart tests have passed
