apiversion: v1
kind: verify-report
metadata:
    tool:
        verifier-version: 1.14.0
        profile:
            VendorType: partner
            version: v1.3
        reportDigest: uint64:2390628901895923031
        chart-uri: N/A
        digests:
            chart: sha256:9c08465b308e09a0b4a9dfc19a7b9f8e15d5ba4ca52fda901add57bc3b23f4b9
            package: 0863fe86a230c6660a494ee6af11dfb8f2918fffbcd96b8995dd56d7bd61373d
        lastCertifiedTimestamp: "2026-01-20T16:43:47.618926+00:00"
        testedOpenShiftVersion: "4.18"
        supportedOpenShiftVersions: '>=4.9'
        webCatalogOnly: true
    chart:
        name: noname-security-sensor-ubi
        home: ""
        sources: []
        version: 3.3.52-rhel
        description: A Helm chart for Kubernetes
        keywords: []
        maintainers: []
        icon: ""
        apiversion: v2
        condition: ""
        tags: ""
        appversion: 3.3.52-rhel
        deprecated: false
        annotations:
            charts.openshift.io/name: noname-security-sensor
        kubeversion: '>=1.22.0-0'
        dependencies: []
        type: application
    chart-overrides: ""
results:
    - check: v1.0/required-annotations-present
      type: Mandatory
      outcome: PASS
      reason: All required annotations present
    - check: v1.0/contains-values
      type: Mandatory
      outcome: PASS
      reason: Values file exist
    - check: v1.0/has-notes
      type: Optional
      outcome: FAIL
      reason: Chart does not contain NOTES.txt
    - check: v1.0/helm-lint
      type: Mandatory
      outcome: PASS
      reason: Helm lint successful
    - check: v1.0/not-contains-crds
      type: Mandatory
      outcome: PASS
      reason: Chart does not contain CRDs
    - check: v1.0/signature-is-valid
      type: Mandatory
      outcome: SKIPPED
      reason: 'Chart is not signed : Signature verification not required'
    - check: v1.1/has-kubeversion
      type: Mandatory
      outcome: PASS
      reason: Kubernetes version specified
    - check: v1.0/is-helm-v3
      type: Mandatory
      outcome: PASS
      reason: API version is V2, used in Helm 3
    - check: v1.0/contains-values-schema
      type: Mandatory
      outcome: PASS
      reason: Values schema file exist
    - check: v1.0/has-readme
      type: Mandatory
      outcome: PASS
      reason: Chart has a README
    - check: v1.0/not-contain-csi-objects
      type: Mandatory
      outcome: PASS
      reason: CSI objects do not exist
    - check: v1.0/chart-testing
      type: Mandatory
      outcome: PASS
      reason: Chart tests have passed
    - check: v1.0/contains-test
      type: Mandatory
      outcome: PASS
      reason: Chart test files exist
    - check: v1.1/images-are-certified
      type: Mandatory
      outcome: PASS
      reason: 'Image is Red Hat certified : us-central1-docker.pkg.dev/noname-artifacts/nns-docker/noname-sensor:3.3.52-rhel'
