apiversion: v1
kind: verify-report
metadata:
    tool:
        verifier-version: 1.14.0
        profile:
            VendorType: partner
            version: v1.3
        reportDigest: uint64:4535158586024423558
        chart-uri: /kb-charts/kb-cloud-installer
        digests:
            chart: sha256:d38a1f3a8807c1c435eb3994b12bd624ee92c016051451ec8eaa6e5684fe4ee7
        lastCertifiedTimestamp: "2026-01-24T02:40:42.322484+00:00"
        testedOpenShiftVersion: "4.19"
        supportedOpenShiftVersions: '>=4.7'
        webCatalogOnly: false
    chart:
        name: kb-cloud-installer
        home: https://kubeblocks.com
        sources: []
        version: 2.1.35
        description: A Helm chart for installing/uninstalling/upgrading the KubeBlocks Enterprise, include the dependency components. KubeBlocks Enterprise is a ready-to-use database management platform enabling users to run and manage multiple types of databases on Kubernetes.
        keywords:
            - kubernetes
            - kubeblocks
            - database
            - streaming
            - message queue
            - dbaas
            - mysql
            - postgresql
            - redis
            - mongodb
        maintainers:
            - name: KubeBlocks Inc.
              email: support@kubeblocks.com
              url: https://kubeblocks.com
        icon: https://kubeblocks.com/logo.png
        apiversion: v2
        condition: ""
        tags: ""
        appversion: 2.1.35
        deprecated: false
        annotations:
            charts.openshift.io/name: kb-cloud-installer
            charts.openshift.io/provider: KubeBlocks Inc.
            charts.openshift.io/supportURL: https://kubeblocks.com/contact
        kubeversion: '>=1.20.0-0'
        dependencies: []
        type: application
    chart-overrides: ""
results:
    - check: v1.0/has-notes
      type: Optional
      outcome: PASS
      reason: Chart does contain NOTES.txt
    - check: v1.1/images-are-certified
      type: Mandatory
      outcome: PASS
      reason: 'Image is Red Hat certified : docker.io/apecloud/kb-cloud-installer:v2.1.42-certified'
    - check: v1.0/chart-testing
      type: Mandatory
      outcome: PASS
      reason: Chart tests have passed
    - check: v1.1/has-kubeversion
      type: Mandatory
      outcome: PASS
      reason: Kubernetes version specified
    - check: v1.0/has-readme
      type: Mandatory
      outcome: PASS
      reason: Chart has a README
    - check: v1.0/helm-lint
      type: Mandatory
      outcome: PASS
      reason: Helm lint successful
    - check: v1.0/is-helm-v3
      type: Mandatory
      outcome: PASS
      reason: API version is V2, used in Helm 3
    - check: v1.0/not-contain-csi-objects
      type: Mandatory
      outcome: PASS
      reason: CSI objects do not exist
    - check: v1.0/not-contains-crds
      type: Mandatory
      outcome: PASS
      reason: Chart does not contain CRDs
    - check: v1.0/contains-values-schema
      type: Mandatory
      outcome: PASS
      reason: Values schema file exist
    - check: v1.0/signature-is-valid
      type: Mandatory
      outcome: SKIPPED
      reason: 'Chart is not signed : Signature verification not required'
    - check: v1.0/required-annotations-present
      type: Mandatory
      outcome: PASS
      reason: All required annotations present
    - check: v1.0/contains-test
      type: Mandatory
      outcome: PASS
      reason: Chart test files exist
    - check: v1.0/contains-values
      type: Mandatory
      outcome: PASS
      reason: Values file exist