apiversion: v1
kind: verify-report
metadata:
    tool:
        verifier-version: 1.0.0
        chart-uri: /charts/awesome-0.1.0.tgz
        digest: sha256:357f067395dfb6c97032bdca4a7e94f6f8cb1df0d3df5684ec71b6552737b767
        lastCertifiedTime: 2021-04-29 06:41:35.248170916 +0000 UTC m=+9.888089220
        certifiedOpenShiftVersions: ""
    chart:
        name: awesome
        home: ""
        sources: []
        version: 0.1.0
        description: A Helm chart for Awesomeness
        keywords: []
        maintainers: []
        icon: https://www.example.com/chart-icon.png
        apiversion: v2
        condition: ""
        tags: ""
        appversion: 1.16.0
        deprecated: false
        annotations:
            helm-chart.openshift.io/archs: all
            helm-chart.openshift.io/name: get your awesomeness here
            helm-chart.openshift.io/provider: acme
            helm-chart.openshift.io/supportURL: http://acme-help-is-here.com/
        kubeversion: ^1.15.0
        dependencies: []
        type: application
    overrides: ""
results:
  - check: not-contains-crds
    type: Mandatory
    outcome: PASS
    reason: Chart does not contain CRDs
  - check: helm-lint
    type: Mandatory
    outcome: PASS
    reason: Helm lint successful
  - check: images-are-certified
    type: Mandatory
    outcome: PASS
    reason: |-
        Image is Red Hat certified : nginx:latest
        Image is Red Hat certified : snyk/kubernetes-operator
  - check: is-helm-v3
    type: Mandatory
    outcome: PASS
    reason: API version is V2, used in Helm 3
  - check: contains-test
    type: Mandatory
    outcome: PASS
    reason: Chart test files exist
  - check: contains-values-schema
    type: Mandatory
    outcome: PASS
    reason: Values schema file exist
  - check: has-minkubeversion
    type: Mandatory
    outcome: PASS
    reason: Minimum Kubernetes version specified
  - check: has-readme
    type: Mandatory
    outcome: PASS
    reason: Chart has a README
  - check: contains-values
    type: Mandatory
    outcome: PASS
    reason: Values file exist
  - check: not-contain-csi-objects
    type: Mandatory
    outcome: PASS
    reason: CSI objects do not exist

