apiVersion: v2
name: expanso-edge
description: Expanso Edge Compute Node for edge computing workloads
type: application
version: 2.1.7
appVersion: "2.1.7"
kubeVersion: ">=1.24.0-0"
home: https://expanso.io
sources:
  - https://github.com/expanso/expanso-edge
keywords:
  - edge-computing
  - compute-node
  - expanso
  - openshift
  - kubernetes
maintainers:
  - name: Expanso Team
    email: support@expanso.io
annotations:
  charts.openshift.io/name: expanso-edge
