apiversion: v1
kind: verify-report
metadata:
    tool:
        verifier-version: 1.12.2
        profile:
            VendorType: partner
            version: v1.2
        reportDigest: uint64:18160743463906871921
        chart-uri: N/A
        digests:
            chart: sha256:b7608f83077438d6ec07f4159042d8917137d967ded84f559d522565c6937acc
            package: 3b7a9d856c4a674f8678aabf1140d9d1610fa3de07dd35f8e8dc69dd22db3426
        lastCertifiedTimestamp: "2025-01-23T18:07:44.851864+00:00"
        testedOpenShiftVersion: 4.16.16
        supportedOpenShiftVersions: '>=4.7'
        webCatalogOnly: true
    chart:
        name: yingoneshotdemo
        home: ""
        sources: []
        version: 0.1.7
        description: A Helm chart for Kubernetes
        keywords: []
        maintainers: []
        icon: https://www.example.com/chart-icon.png
        apiversion: v2
        condition: ""
        tags: ""
        appversion: 1-24
        deprecated: false
        annotations:
            charts.openshift.io/archs: x86_64
            charts.openshift.io/name: RedHat Test
            charts.openshift.io/provider: RedHat
            charts.openshift.io/supportURL: https://github.com/ansvu/yingoneshotdemo
        kubeversion: '>=1.20.0'
        dependencies: []
        type: application
    chart-overrides: ""
results:
    - check: v1.0/not-contain-csi-objects
      type: Mandatory
      outcome: PASS
      reason: CSI objects do not exist
    - check: v1.0/signature-is-valid
      type: Mandatory
      outcome: SKIPPED
      reason: 'Chart is not signed : Signature verification not required'
    - check: v1.0/chart-testing
      type: Mandatory
      outcome: PASS
      reason: Chart tests have passed
    - check: v1.0/contains-test
      type: Mandatory
      outcome: PASS
      reason: Chart test files exist
    - check: v1.0/helm-lint
      type: Mandatory
      outcome: PASS
      reason: Helm lint successful
    - check: v1.0/is-helm-v3
      type: Mandatory
      outcome: PASS
      reason: API version is V2, used in Helm 3
    - check: v1.0/required-annotations-present
      type: Mandatory
      outcome: PASS
      reason: All required annotations present
    - check: v1.0/contains-values-schema
      type: Mandatory
      outcome: PASS
      reason: Values schema file exist
    - check: v1.1/has-kubeversion
      type: Mandatory
      outcome: PASS
      reason: Kubernetes version specified
    - check: v1.0/contains-values
      type: Mandatory
      outcome: PASS
      reason: Values file exist
    - check: v1.0/not-contains-crds
      type: Mandatory
      outcome: PASS
      reason: Chart does not contain CRDs
    - check: v1.0/has-readme
      type: Mandatory
      outcome: PASS
      reason: Chart has a README
    - check: v1.1/images-are-certified
      type: Mandatory
      outcome: PASS
      reason: |-
        Image is Red Hat certified : quay.io/avu0/ying-nginx-oneshot1-8080:1-24
        Image is Red Hat certified : quay.io/avu0/ying-nginx-oneshot1-8081:1-24
