{{- define "createRoute" }}
{{- $svcName := index . 0 }}
{{- $targetPort := index . 1 }}
{{- $ := index . 2 }}
{{- with index . 3 }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $svcName }}
  {{- $labels := include "cryostat.labels" $ | nindent 4 }}
  labels: {{ $labels }}
  {{- with .route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  to:
    kind: Service
    name: {{ $svcName }}
  port:
    targetPort: {{ $targetPort }}
{{- if .route.tls.enabled }}
  tls:
    termination: {{ .route.tls.termination }}
    insecureEdgeTerminationPolicy: {{ .route.tls.insecureEdgeTerminationPolicy }}
  {{- if .route.tls.key }}
    key: |-
      {{- .route.tls.key | nindent 6 }}
  {{- end }}
  {{- if .route.tls.destinationCACertificate }}
    destinationCACertificate: |-
      {{- .route.tls.destinationCACertificate | nindent 6 }}
  {{- end }}
  {{- if .route.tls.caCertificate }}
    caCertificate: |-
      {{- .route.tls.caCertificate | nindent 6 }}
  {{- end }}
  {{- if .route.tls.certificate }}
    certificate: |-
      {{- .route.tls.certificate | nindent 6 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}

{{- $fullName := include "cryostat.fullname" . -}}
{{- if .Values.core.route.enabled }}
{{- include "createRoute" (list $fullName 8181 $ .Values.core)}}
{{- end }}
{{- if .Values.grafana.route.enabled }}
{{- include "createRoute" (list (printf "%s-%s" $fullName "grafana") 3000 $ .Values.grafana)}}
{{- end }}
