apiversion: v1
kind: verify-report
metadata:
    tool:
        verifier-version: 1.7.0
        profile:
            VendorType: partner
            version: v1.1
        chart-uri: http://jumpbox.partnerci.bos2.lab/charts/samplechart-0.1.2.tgz
        digests:
            chart: sha256:4abe3a57dcc5865e006b8165507a06b4f165b282a53afb3060a1ff0733c4f2dd
            package: 83770ebbecceabdfe413e37692c89344f8e1c9951fb4be68f083834815c864f2
        lastCertifiedTimestamp: "2022-07-06T01:34:49.552863+00:00"
        testedOpenShiftVersion: "4.10"
        supportedOpenShiftVersions: '>=4.7'
        providerControlledDelivery: false
    chart:
        name: samplechart
        home: ""
        sources: []
        version: 0.1.2
        description: A Helm chart for Kubernetes
        keywords: []
        maintainers: []
        icon: https://www.example.com/chart-icon.png
        apiversion: v2
        condition: ""
        tags: ""
        appversion: 1-42
        deprecated: false
        annotations:
            charts.openshift.io/archs: x86_64
            charts.openshift.io/name: RedHat Test
            charts.openshift.io/provider: RedHat
            charts.openshift.io/supportURL: https://github.com/dperaza4dustbit/helm-chart
        kubeversion: '>=1.20.0'
        dependencies: []
        type: application
    chart-overrides: ""
results:
    - check: v1.0/contains-test
      type: Mandatory
      outcome: PASS
      reason: Chart test files exist
    - check: v1.0/not-contains-crds
      type: Mandatory
      outcome: PASS
      reason: Chart does not contain CRDs
    - check: v1.0/not-contain-csi-objects
      type: Mandatory
      outcome: PASS
      reason: CSI objects do not exist
    - check: v1.0/chart-testing
      type: Mandatory
      outcome: PASS
      reason: Chart tests have passed
    - check: v1.1/has-kubeversion
      type: Mandatory
      outcome: PASS
      reason: Kubernetes version specified
    - check: v1.0/helm-lint
      type: Mandatory
      outcome: PASS
      reason: Helm lint successful
    - check: v1.0/images-are-certified
      type: Mandatory
      outcome: PASS
      reason: 'Image is Red Hat certified : registry.access.redhat.com/ubi8/nginx-118:1-42'
    - check: v1.0/required-annotations-present
      type: Mandatory
      outcome: PASS
      reason: All required annotations present
    - check: v1.0/has-readme
      type: Mandatory
      outcome: PASS
      reason: Chart has a README
    - check: v1.0/is-helm-v3
      type: Mandatory
      outcome: PASS
      reason: API version is V2, used in Helm 3
    - check: v1.0/contains-values
      type: Mandatory
      outcome: PASS
      reason: Values file exist
    - check: v1.0/contains-values-schema
      type: Mandatory
      outcome: PASS
      reason: Values schema file exist
