apiversion: v1
kind: verify-report
metadata:
    tool:
        verifier-version: 1.9.0
        profile:
            VendorType: partner
            version: v1.2
        reportDigest: uint64:1594989441813019293
        chart-uri: /charts/illumio-4.0.0.tgz
        digests:
            chart: sha256:7b56401ba5858f1178bc2a67fc72468512e2d47041505d90320540e4325cc138
            package: b9ecf4d4133d8b3e272ab21a252bf1c555e4cd9f67f9dcac86ec38ac4236932a
        lastCertifiedTimestamp: "2023-01-23T20:54:18.442756+00:00"
        testedOpenShiftVersion: "4.11"
        supportedOpenShiftVersions: '>=4.7'
        providerControlledDelivery: false
    chart:
        name: illumio
        home: ""
        sources: []
        version: 4.0.0
        description: A Helm chart of Illumio Core for Kubernetes
        keywords: []
        maintainers: []
        icon: https://www.illumio.com/sites/default/files/2021-05/illumio_Logo_2019_0_OPT.svg
        apiversion: v2
        condition: ""
        tags: ""
        appversion: 4.0.0
        deprecated: false
        annotations:
            charts.openshift.io/name: Illumio Core for Kubernetes
        kubeversion: '>=1.20.0-0'
        dependencies: []
        type: application
    chart-overrides: ""
results:
    - check: v1.0/has-readme
      type: Mandatory
      outcome: PASS
      reason: Chart has a README
    - check: v1.0/contains-values-schema
      type: Mandatory
      outcome: PASS
      reason: Values schema file exist
    - check: v1.0/contains-values
      type: Mandatory
      outcome: PASS
      reason: Values file exist
    - check: v1.0/not-contain-csi-objects
      type: Mandatory
      outcome: PASS
      reason: CSI objects do not exist
    - check: v1.0/required-annotations-present
      type: Mandatory
      outcome: PASS
      reason: All required annotations present
    - check: v1.0/chart-testing
      type: Mandatory
      outcome: PASS
      reason: Chart tests have passed
    - check: v1.1/has-kubeversion
      type: Mandatory
      outcome: PASS
      reason: Kubernetes version specified
    - check: v1.0/is-helm-v3
      type: Mandatory
      outcome: PASS
      reason: API version is V2, used in Helm 3
    - check: v1.0/signature-is-valid
      type: Mandatory
      outcome: SKIPPED
      reason: 'Chart is not signed : Signature verification not required'
    - check: v1.0/contains-test
      type: Mandatory
      outcome: PASS
      reason: Chart test files exist
    - check: v1.0/helm-lint
      type: Mandatory
      outcome: PASS
      reason: Helm lint successful
    - check: v1.1/images-are-certified
      type: Mandatory
      outcome: PASS
      reason: |-
        Image is Red Hat certified : quay.io/illumio/cven:22.5.11-9729
        Image is Red Hat certified : quay.io/illumio/kubelink:3.2.0.7b7a38
        Image is Red Hat certified : registry.access.redhat.com/ubi9/toolbox:9.0.0-13
    - check: v1.0/not-contains-crds
      type: Mandatory
      outcome: PASS
      reason: Chart does not contain CRDs

