apiversion: v1
kind: verify-report
metadata:
    tool:
        verifier-version: 1.13.13
        profile:
            VendorType: partner
            version: v1.3
        reportDigest: uint64:13129541182991460240
        chart-uri: ./voyager-gateway-2026.1.15.tgz
        digests:
            chart: sha256:2f0cd4b5163a46b5386db672ce11b70929aeed21cb170703223ae6d4a511244e
            package: ac3a849e84d9bc03657068827a3779123f76b74c094a61200faaafbc8e45e79f
        lastCertifiedTimestamp: "2026-01-27T10:54:49.052023+06:00"
        testedOpenShiftVersion: "4.18"
        supportedOpenShiftVersions: '>=4.15'
        webCatalogOnly: false
    chart:
        name: voyager-gateway
        home: https://gateway.voyagermesh.com/
        sources:
            - https://github.com/voyagermesh/gateway
        version: 2026.1.15
        description: The Helm chart for Voyager Gateway
        keywords:
            - gateway-api
            - envoyproxy
            - envoy-gateway
            - eg
        maintainers:
            - name: appscode
              email: support@appscode.com
              url: ""
        icon: ""
        apiversion: v2
        condition: ""
        tags: ""
        appversion: v1.6.2
        deprecated: false
        annotations:
            charts.openshift.io/name: voyager-gateway
        kubeversion: '>=1.28.0'
        dependencies:
            - name: gateway-converter
              version: v2024.8.30
              repository: file://../gateway-converter
              condition: gateway-converter.enabled
            - name: crd-manager
              version: v2026.1.15
              repository: file://../crd-manager
              condition: crd-manager.enabled
        type: application
    chart-overrides: ""
results:
    - check: v1.0/contains-values-schema
      type: Mandatory
      outcome: PASS
      reason: Values schema file exist
    - check: v1.0/has-notes
      type: Optional
      outcome: PASS
      reason: Chart does contain NOTES.txt
    - check: v1.1/images-are-certified
      type: Mandatory
      outcome: PASS
      reason: |-
        Image is Red Hat certified : ghcr.io/voyagermesh/ratelimit:v2026.1.15-ubi
        Image is Red Hat certified : ghcr.io/voyagermesh/gateway:v1.6.2-ubi
        Image is Red Hat certified : ghcr.io/appscode/kubectl-nonroot:1.34-ubi
        Image is Red Hat certified : ghcr.io/voyagermesh/crd-manager:v0.1.0-ubi
    - check: v1.0/not-contains-crds
      type: Mandatory
      outcome: PASS
      reason: Chart does not contain CRDs
    - check: v1.0/required-annotations-present
      type: Mandatory
      outcome: PASS
      reason: All required annotations present
    - check: v1.0/has-readme
      type: Mandatory
      outcome: PASS
      reason: Chart has a README
    - check: v1.0/not-contain-csi-objects
      type: Mandatory
      outcome: PASS
      reason: CSI objects do not exist
    - check: v1.0/chart-testing
      type: Mandatory
      outcome: PASS
      reason: Chart tests have passed
    - check: v1.1/has-kubeversion
      type: Mandatory
      outcome: PASS
      reason: Kubernetes version specified
    - check: v1.0/contains-test
      type: Mandatory
      outcome: PASS
      reason: Chart test files exist
    - check: v1.0/contains-values
      type: Mandatory
      outcome: PASS
      reason: Values file exist
    - check: v1.0/helm-lint
      type: Mandatory
      outcome: PASS
      reason: Helm lint successful
    - check: v1.0/is-helm-v3
      type: Mandatory
      outcome: PASS
      reason: API version is V2, used in Helm 3
    - check: v1.0/signature-is-valid
      type: Mandatory
      outcome: SKIPPED
      reason: 'Chart is not signed : Signature verification not required'

