# Copyright (c) 2020, Oracle Corporation and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
annotations:
  charts.openshift.io/name: Oracle 12c Database Server
  charts.openshift.io/provider: Maximiliano Pizarro
  charts.openshift.io/supportURL: https://access.redhat.com/support
apiVersion: v2
description: Oracle 12c Database Server
home: https://maximilianopizarro.github.io/oracle-helm-charts/
name: oracle12c
version: 0.1.0
appVersion: "12.2.0.1"
keywords:
- oracle
- database
- openshift
maintainers: 
  - name: Maximiliano Pizarro
    email: maximiliano.pizarro.5@gmail.com
    url: http://www.linkedin.com/in/maximiliano-gregorio-pizarro-consultor-it

icon: https://raw.githubusercontent.com/maximilianoPizarro/oracle-helm-charts/main/oracle-icon.png