apiversion: v1
kind: verify-report
metadata:
    tool:
        verifier-version: 1.0.0
        chart-uri: /charts/src
        digest: sha256:3d726729e0f72b364c5dd7f535ac44e356ca6b2c471e1b8011b902b943596a55
        lastCertifiedTimestamp: "2021-05-18T21:27:31.834545+00:00"
        certifiedOpenShiftVersions: 4.7.8
    chart:
        name: acme
        home: ""
        sources: []
        version: 0.1.0
        description: A Helm chart for Awesomeness
        keywords: []
        maintainers: []
        icon: https://www.example.com/chart-icon.png
        apiversion: v2
        condition: ""
        tags: ""
        appversion: 1.16.0
        deprecated: false
        annotations:
            charts.openshift.io/archs: all
            charts.openshift.io/name: get your awesomeness here
            charts.openshift.io/provider: test-org1
            charts.openshift.io/supportURL: http://acme-help-is-here.com/
        kubeversion: 1.20.0
        dependencies: []
        type: application
    overrides: ""
results:
  - check: contains-values
    type: Mandatory
    outcome: PASS
    reason: Values file exist
  - check: has-kubeversion
    type: Mandatory
    outcome: PASS
    reason: Kubernetes version specified
  - check: helm-lint
    type: Mandatory
    outcome: PASS
    reason: Helm lint successful
  - check: not-contain-csi-objects
    type: Mandatory
    outcome: PASS
    reason: CSI objects do not exist
  - check: images-are-certified
    type: Mandatory
    outcome: PASS
    reason: |-
        Image is Red Hat certified : nginx:latest
        Image is Red Hat certified : snyk/kubernetes-operator
  - check: chart-testing
    type: Mandatory
    outcome: PASS
    reason: 'Error waiting for process: exit status 1'
  - check: has-readme
    type: Mandatory
    outcome: PASS
    reason: Chart has a README
  - check: is-helm-v3
    type: Mandatory
    outcome: PASS
    reason: API version is V2, used in Helm 3
  - check: contains-test
    type: Mandatory
    outcome: PASS
    reason: Chart test files exist
  - check: contains-values-schema
    type: Mandatory
    outcome: PASS
    reason: Values schema file exist
  - check: not-contains-crds
    type: Mandatory
    outcome: PASS
    reason: Chart does not contain CRDs

