apiversion: v1
kind: verify-report
metadata:
    tool:
        verifier-version: 1.6.0
        profile:
            VendorType: partner
            version: v1.1
        chart-uri: https://github.com/ansvu/samplechart/releases/du_helmchart/du_helmchart_run.tgz
        digests:
            chart: sha256:75ca3bacbe48389a2273a216571db8d996336dca73feb8005b10d68f490044f2
            package: a96538a7d87eaf005e7a4b095b9fb314a96dfa2d570c283698b63ebbbd1a424f
        lastCertifiedTimestamp: "2022-06-11T16:49:30.472769+00:00"
        testedOpenShiftVersion: "4.9"
        supportedOpenShiftVersions: '>=4.5'
        providerControlledDelivery: false
    chart:
        name: du
        home: ""
        sources: []
        version: du5.0.326-53
        description: NF Service template.
        keywords: []
        maintainers:
            - name: ran ptf team
              email: srikanth.subbaramu@mavenir.com
              url: ""
        icon: ""
        apiversion: v2
        condition: ""
        tags: ""
        appversion: "0.1"
        deprecated: false
        annotations:
            charts.openshift.io/name: test
        kubeversion: '>=1.18.0-0'
        dependencies: []
        type: ""
    chart-overrides: ""
results:
    - check: v1.0/has-readme
      type: Mandatory
      outcome: PASS
      reason: Chart has a README
    - check: v1.0/is-helm-v3
      type: Mandatory
      outcome: PASS
      reason: API version is V2, used in Helm 3
    - check: v1.0/contains-test
      type: Mandatory
      outcome: PASS
      reason: Chart test files exist
    - check: v1.0/contains-values
      type: Mandatory
      outcome: PASS
      reason: Values file exist
    - check: v1.0/contains-values-schema
      type: Mandatory
      outcome: PASS
      reason: Values schema file exist
    - check: v1.0/not-contains-crds
      type: Mandatory
      outcome: PASS
      reason: Chart does not contain CRDs
    - check: v1.0/not-contain-csi-objects
      type: Mandatory
      outcome: PASS
      reason: CSI objects do not exist
    - check: v1.1/has-kubeversion
      type: Mandatory
      outcome: PASS
      reason: Kubernetes version specified
    - check: v1.0/helm-lint
      type: Mandatory
      outcome: PASS
      reason: Helm lint successful
    - check: v1.0/images-are-certified
      type: Mandatory
      outcome: PASS
      reason: |-
        Image is Red Hat certified : quay.io/mrhcert/du
    - check: v1.0/chart-testing
      type: Mandatory
      outcome: PASS
      reason: Chart tests have passed
    - check: v1.0/required-annotations-present
      type: Mandatory
      outcome: PASS
      reason: All required annotations present
