apiversion: v1
kind: verify-report
metadata:
    tool:
        verifier-version: 1.7.0
        profile:
            VendorType: partner
            version: v1.1
        chart-uri: https://github.com/IBM/charts/blob/master/repo/ibm-helm/ibm-object-storage-plugin-2.2.5.tgz?raw=true
        digests:
            chart: sha256:f5bee25bdf4e9f4391539912efdaeb5706dc656a86f8b00b724e0ecea81e4beb
        lastCertifiedTimestamp: "2022-12-15T06:09:06.885092+00:00"
        testedOpenShiftVersion: "4.10"
        supportedOpenShiftVersions: '>=4.6'
        providerControlledDelivery: false
    chart:
        name: ibm-object-storage-plugin
        home: ""
        sources: []
        version: 2.2.5
        description: 'Chart for deploying ibmcloud object storage plugin. IBM Cloud Object Storage is persistent, highly available storage that you can mount to apps that run in a Kubernetes cluster by using the IBM Cloud Object Storage plug-in. The plug-in is a Kubernetes Flex-Volume plug-in that connects Cloud Object Storage buckets to pods in your cluster.  License By installing this product you accept the following license terms: http://www.apache.org/licenses/ and https://www.redhat.com/licenses/EULA_Red_Hat_Universal_Base_Image_English_20190422.pdf'
        keywords:
            - IKS
            - amd64
            - Storage
            - Commercial
            - Limited
            - Other
            - ROKS
        maintainers:
            - name: IBM
              email: contsto2@in.ibm.com
              url: ""
        icon: https://cache.globalcatalog.cloud.ibm.com/static/cache/2461-acb0d10a1725d783/images/uploaded/icons/object-storage.png
        apiversion: v2
        condition: ""
        tags: ""
        appversion: 2.2.5
        deprecated: false
        annotations:
            charts.openshift.io/name: ibm-object-storage-plugin Chart
        kubeversion: '>=1.19.0'
        dependencies: []
        type: ""
    chart-overrides: ""
results:
    - check: v1.0/contains-test
      type: Mandatory
      outcome: PASS
      reason: Chart test files exist
    - check: v1.0/contains-values
      type: Mandatory
      outcome: PASS
      reason: Values file exist
    - check: v1.0/contains-values-schema
      type: Mandatory
      outcome: PASS
      reason: Values schema file exist
    - check: v1.0/helm-lint
      type: Mandatory
      outcome: PASS
      reason: Helm lint successful
    - check: v1.0/images-are-certified
      type: Mandatory
      outcome: PASS
      reason: |-
        Image is Red Hat certified : icr.io/cpopen/ibmcloud-object-storage-driver@sha256:33288d7a6d0eca2db4d918a9249b94af9748bd083764dc156d58a34283692b70
        Image is Red Hat certified : icr.io/cpopen/ibmcloud-object-storage-plugin@sha256:808da1fa5f7b275bf5f56f5933bd90e6a840345a6ee177c302c1181c7c7be7ca
    - check: v1.0/chart-testing
      type: Mandatory
      outcome: PASS
      reason: Chart tests have passed
    - check: v1.0/has-readme
      type: Mandatory
      outcome: PASS
      reason: Chart has a README
    - check: v1.0/is-helm-v3
      type: Mandatory
      outcome: PASS
      reason: API version is V2, used in Helm 3
    - check: v1.0/not-contain-csi-objects
      type: Mandatory
      outcome: PASS
      reason: CSI objects do not exist
    - check: v1.0/required-annotations-present
      type: Mandatory
      outcome: PASS
      reason: All required annotations present
    - check: v1.1/has-kubeversion
      type: Mandatory
      outcome: PASS
      reason: Kubernetes version specified
    - check: v1.0/not-contains-crds
      type: Mandatory
      outcome: PASS
      reason: Chart does not contain CRDs 
