description: |-
  This content is experimental, do not use it in production. Python imagestreams for using on OpenShift 4.
  For more information about using this builder image, including OpenShift considerations,
  see https://github.com/sclorg/s2i-python-container/blob/master/3.11/README.md.
annotations:
  charts.openshift.io/name: Red Hat Python imagestreams (experimental).
  charts.openshift.io/provider: Red Hat
  charts.openshift.io/providerType: redhat
apiVersion: v2
appVersion: 0.0.2
kubeVersion: '>=1.20.0'
name: redhat-python-imagestreams
tags: builder,python
sources:
  - https://github.com/sclorg/helm-charts
version: 0.0.2
