apiversion: v1
kind: verify-report
metadata:
    tool:
        verifier-version: 1.13.12
        profile:
            VendorType: partner
            version: v1.3
        reportDigest: uint64:6714166869294143443
        chart-uri: /charts/alquimia-studio-0.2.0.tgz
        digests:
            chart: sha256:b39161d9de173f651bac36df960fc804e7a6f4628e7ebb36ba182118849803dc
            package: 5c10a8dbf967213d0b3cc9af13c02a427b149495dc948aa5bd8ac3b78d2b5c8b
        lastCertifiedTimestamp: "2025-12-17T12:43:25.173057+00:00"
        testedOpenShiftVersion: "4.19"
        supportedOpenShiftVersions: '>=4.13'
        webCatalogOnly: false
    chart:
        name: alquimia-studio
        home: https://github.com/Alquimia-ai
        sources:
            - https://github.com/Alquimia-ai/studio
        version: 0.2.0
        description: Alquimia Studio â€“ front/app service for Alquimia Platform.
        keywords:
            - alquimia
            - studio
            - nextjs
            - web
        maintainers:
            - name: Alquimia AI
              email: team@alquimia.ai
              url: ""
        icon: https://www.alquimia.ai/favicon.ico
        apiversion: v2
        condition: ""
        tags: ""
        appversion: 1.0.0
        deprecated: false
        annotations:
            charts.openshift.io/links: Documentation,https://github.com/Alquimia-ai/studio
            charts.openshift.io/name: Alquimia Studio
            charts.openshift.io/providerType: community
            charts.openshift.io/supportURL: https://github.com/Alquimia-ai/studio/issues
            charts.openshift.io/supportedOpenShiftVersions: '>=4.15'
        kubeversion: '>=1.26.0-0'
        dependencies: []
        type: application
    chart-overrides: ""
results:
    - check: v1.1/has-kubeversion
      type: Mandatory
      outcome: PASS
      reason: Kubernetes version specified
    - check: v1.0/is-helm-v3
      type: Mandatory
      outcome: PASS
      reason: API version is V2, used in Helm 3
    - check: v1.0/contains-test
      type: Mandatory
      outcome: PASS
      reason: Chart test files exist
    - check: v1.0/chart-testing
      type: Mandatory
      outcome: PASS
      reason: Chart tests have passed
    - check: v1.1/images-are-certified
      type: Mandatory
      outcome: PASS
      reason: |-
        Image is Red Hat certified : alquimiaai/studio:certification
        Image is Red Hat certified : registry.access.redhat.com/ubi9/ubi-minimal
    - check: v1.0/contains-values-schema
      type: Mandatory
      outcome: PASS
      reason: Values schema file exist
    - check: v1.0/contains-values
      type: Mandatory
      outcome: PASS
      reason: Values file exist
    - check: v1.0/has-notes
      type: Optional
      outcome: PASS
      reason: Chart does contain NOTES.txt
    - check: v1.0/not-contain-csi-objects
      type: Mandatory
      outcome: PASS
      reason: CSI objects do not exist
    - check: v1.0/required-annotations-present
      type: Mandatory
      outcome: PASS
      reason: All required annotations present
    - check: v1.0/signature-is-valid
      type: Mandatory
      outcome: SKIPPED
      reason: 'Chart is not signed : Signature verification not required'
    - check: v1.0/helm-lint
      type: Mandatory
      outcome: PASS
      reason: Helm lint successful
    - check: v1.0/has-readme
      type: Mandatory
      outcome: PASS
      reason: Chart has a README
    - check: v1.0/not-contains-crds
      type: Mandatory
      outcome: PASS
      reason: Chart does not contain CRDs