apiversion: v1
kind: verify-report
metadata:
  tool:
    verifier-version: 1.0.0
    chart-uri: http://charts.com
    digest: sha256:4d144b8ab80cd33962743318deb50c25ac582de570b7067f8ae7844088872db9
    lastCertifiedTime: 2021-04-22 10:49:29.714918174 +0000 UTC m=+1.932279870
    certifiedOpenShiftVersions: ""
  chart:
    name: helm-demo-chart
    home: ""
    sources: []
    version: 0.1.0
    description: A Helm chart for Kubernetes
    keywords: []
    maintainers: []
    icon: https://www.example.com/chart-icon.png
    apiversion: v2
    condition: ""
    tags: ""
    appversion: 1.16.0
    deprecated: false
    annotations: {}
    kubeversion: 1.20.0
    dependencies: []
    type: application
  overrides: ""
results:
  - check: is-helm-v3
    type: Mandatory
    outcome: PASS
    reason: API version is V2, used in Helm 3
  - check: contains-test
    type: Mandatory
    outcome: PASS
    reason: Chart test files exist
  - check: contains-values
    type: Mandatory
    outcome: PASS
    reason: Values file exist
  - check: helm-lint
    type: Mandatory
    outcome: PASS
    reason: Helm lint successful
  - check: has-readme
    type: Mandatory
    outcome: PASS
    reason: Chart has a README
  - check: contains-values-schema
    type: Mandatory
    outcome: PASS
    reason: Values schema file exist
  - check: has-minkubeversion
    type: Mandatory
    outcome: PASS
    reason: Minimum Kubernetes version specified
  - check: not-contains-crds
    type: Mandatory
    outcome: PASS
    reason: Chart does not contain CRDs
  - check: not-contain-csi-objects
    type: Mandatory
    outcome: PASS
    reason: CSI objects do not exist
  - check: images-are-certified
    type: Mandatory
    outcome: PASS
    reason: Certified

