apiversion: v1
kind: verify-report
metadata:
    tool:
        verifier-version: 1.0.0
        profile:
            VendorType: partner
            version: v1.1
        chart-uri: https://europe-docker.pkg.dev/nfv-ri/helm-charts/nfvri
        digests:
            chart: sha256:001abb541d0be2cc58a5ab6bf75bf0b05023ef37f40f9129ff677db7cef603e3
            package: a65ca1921a21c3a90cda7849ebe7355aed87a6dde755d5231bb4a314f2ee1ae1
        lastCertifiedTimestamp: "2022-10-19T09:24:59.061544+00:00"
        testedOpenShiftVersion: "4.10"
        supportedOpenShiftVersions: '>=4.7'
        providerControlledDelivery: false
    chart:
        name: nfvri
        home: ""
        sources: []
        version: 4.4.0
        description: A Helm chart for Kubernetes to deploy the NFV-RI stack
        keywords: []
        maintainers: []
        icon: ""
        apiversion: v2
        condition: ""
        tags: ""
        appversion: v4.4.0
        deprecated: false
        annotations:
            charts.openshift.io/name: nfvri
        kubeversion: '>= 1.20.0'
        dependencies:
            - name: nfvri-agent
              version: 4.4.0
              repository: file://../nfvri-agent
              condition: ""
              tags: []
              enabled: false
              importvalues: []
              alias: ""
            - name: nfvri-apiserver
              version: 4.4.0
              repository: file://../nfvri-apiserver
              condition: ""
              tags: []
              enabled: false
              importvalues: []
              alias: ""
            - name: nfvri-orchestrator
              version: 4.4.0
              repository: file://../nfvri-orchestrator
              condition: ""
              tags: []
              enabled: false
              importvalues: []
              alias: ""
            - name: nfvri-dashboard
              version: 4.4.0
              repository: file://../nfvri-dashboard
              condition: ""
              tags: []
              enabled: false
              importvalues: []
              alias: ""
        type: application
    chart-overrides: ""
results:
    - check: v1.0/contains-values-schema
      type: Mandatory
      outcome: PASS
      reason: Values schema file exist
    - check: v1.0/contains-values
      type: Mandatory
      outcome: PASS
      reason: Values file exist
    - check: v1.0/has-readme
      type: Mandatory
      outcome: PASS
      reason: Chart has a README
    - check: v1.1/has-kubeversion
      type: Mandatory
      outcome: PASS
      reason: Kubernetes version specified
    - check: v1.0/helm-lint
      type: Mandatory
      outcome: PASS
      reason: Helm lint successful
    - check: v1.0/not-contains-crds
      type: Mandatory
      outcome: PASS
      reason: Chart does not contain CRDs
    - check: v1.0/required-annotations-present
      type: Mandatory
      outcome: PASS
      reason: All required annotations present
    - check: v1.0/contains-test
      type: Mandatory
      outcome: PASS
      reason: Chart test files exist
    - check: v1.0/images-are-certified
      type: Mandatory
      outcome: PASS
      reason: |-
        Image is Red Hat certified : europe-docker.pkg.dev/nfv-ri/images/dc-agent-rhel8:v4.4.0
        Image is Red Hat certified : europe-docker.pkg.dev/nfv-ri/images/apiserver-ubi8:v4.4.0
        Image is Red Hat certified : europe-docker.pkg.dev/nfv-ri/images/dashboard-ubi8:v4.4.0
        Image is Red Hat certified : europe-docker.pkg.dev/nfv-ri/images/orchestrator-rhel8:v4.4.0
        Image is Red Hat certified : registry.access.redhat.com/ubi8/ubi:8.4-206
    - check: v1.0/is-helm-v3
      type: Mandatory
      outcome: PASS
      reason: API version is V2, used in Helm 3
    - check: v1.0/not-contain-csi-objects
      type: Mandatory
      outcome: PASS
      reason: CSI objects do not exist
    - check: v1.0/chart-testing
      type: Mandatory
      outcome: PASS
      reason: Chart tests have passed