name: Python Style

on:
  pull_request:
    paths:
    # Only trigger on core script changes
    - 'scripts/**.py'

jobs:
  enforce:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: ./.github/actions/setup-python
    - name: Install style tooling
      working-directory: scripts
      run: make venv.codestyle
    - name: Run formatter
      working-directory: scripts
      run: make ci.format
      # Temporarily auto-pass linting until we are able to manually review and
      # address.
    - name: Run linter
      working-directory: scripts
      run: make lint || true