name: Release Charts

on:
  push: {}

concurrency: chart_index-${{ github.ref }}

jobs:
  release-charts:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Release Charts
        env:
          GITHUB_REF: ${{ github.ref }}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          curl -L -o cr.tar.gz https://github.com/helm/chart-releaser/releases/download/v1.2.0/chart-releaser_1.2.0_linux_amd64.tar.gz
          tar zxvf cr.tar.gz
          sudo cp -f cr /usr/local/bin/cr
          python3 -m venv ve1
          cd scripts && ../ve1/bin/pip3 install -r requirements.txt && cd ..
          docker pull quay.io/redhat-certification/chart-verifier:latest
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
          cd scripts && ../ve1/bin/python3 setup.py install && cd ..
          INDEX_BRANCH=$(if [ "${GITHUB_REF}" = "main" ]; then echo "refs/heads/gh-pages"; else echo "${GITHUB_REF}-gh-pages"; fi)
          ve1/bin/chart-repo-manager --index-branch=${INDEX_BRANCH}
