{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "expanso-edge-compute.fullname" . }}
  labels:
    {{- include "expanso-edge-compute.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: api
  selector:
    {{- include "expanso-edge-compute.selectorLabels" . | nindent 4 }}
{{- end }}
