apiversion: v1
kind: verify-report
metadata:
    tool:
        verifier-version: 1.4.1
        profile:
            VendorType: partner
            version: v1.1
        chart-uri: /charts/_build/wavefront-1.7.10.tgz
        digests:
            chart: sha256:594cb8be9013c9dd98c89693878f35c3b632c7b7465ab83cdaa0d31c71acc57c
            package: 89f74153cbe57e617a49a16993daf1a13eef31a375fbdbb4c3e501c28d0bb25a
        lastCertifiedTimestamp: "2021-12-20T22:13:45.725332+00:00"
        testedOpenShiftVersion: "4.9"
        supportedOpenShiftVersions: '>=4.6'
    chart:
        name: wavefront
        home: https://www.wavefront.com
        sources:
            - https://github.com/wavefrontHQ/wavefront-collector-for-kubernetes
            - https://github.com/wavefrontHQ/wavefront-proxy
        version: 1.7.10
        description: Wavefront Collector for Kubernetes
        keywords:
            - metric
            - monitoring
            - observability
            - alerting
        maintainers:
            - name: akodali18
              email: akodali@vmware.com
              url: ""
            - name: johncornish
              email: jcornish@vmware.com
              url: ""
            - name: josephgee
              email: jgee@vmware.com
              url: ""
            - name: helen-shao
              email: shaoh@vmware.com
              url: ""
            - name: mceldeen
              email: matthewco@vmware.com
              url: ""
            - name: mmichael
              email: mamichael@vmware.com
              url: ""
            - name: priyaselvaganesan
              email: pselvaganesa@vmware.com
              url: ""
        icon: ""
        apiversion: v2
        condition: ""
        tags: ""
        appversion: 1.7.5
        deprecated: false
        annotations:
            charts.openshift.io/name: wavefront
        kubeversion: '>= 1.19'
        dependencies:
            - name: kube-state-metrics
              version: ^2.2.1
              repository: https://charts.helm.sh/stable
              condition: kubeStateMetrics.enabled
              tags: []
              enabled: false
              importvalues: []
              alias: ""
        type: ""
    chart-overrides: ""
results:
    - check: v1.0/is-helm-v3
      type: Mandatory
      outcome: PASS
      reason: API version is V2, used in Helm 3
    - check: v1.0/contains-values
      type: Mandatory
      outcome: PASS
      reason: Values file exist
    - check: v1.0/contains-values-schema
      type: Mandatory
      outcome: PASS
      reason: Values schema file exist
    - check: v1.0/not-contain-csi-objects
      type: Mandatory
      outcome: PASS
      reason: CSI objects do not exist
    - check: v1.0/required-annotations-present
      type: Mandatory
      outcome: PASS
      reason: All required annotations present
    - check: v1.0/has-readme
      type: Mandatory
      outcome: PASS
      reason: Chart has a README
    - check: v1.0/contains-test
      type: Mandatory
      outcome: PASS
      reason: Chart test files exist
    - check: v1.1/has-kubeversion
      type: Mandatory
      outcome: PASS
      reason: Kubernetes version specified
    - check: v1.0/not-contains-crds
      type: Mandatory
      outcome: PASS
      reason: Chart does not contain CRDs
    - check: v1.0/helm-lint
      type: Mandatory
      outcome: PASS
      reason: Helm lint successful
    - check: v1.0/images-are-certified
      type: Mandatory
      outcome: PASS
      reason: |-
        Image is Red Hat certified : registry.connect.redhat.com/wavefronthq/wavefront-kubernetes-collector:1.7.5.1
        Image is Red Hat certified : registry.connect.redhat.com/wavefronthq/proxy:10.12
        Image is Red Hat certified : registry.connect.redhat.com/seldonio/kubectl
    - check: v1.0/chart-testing
      type: Mandatory
      outcome: PASS
      reason: Chart tests have passed
